=== Sinien/aion-lightning-2/trunk/AL-Game/data/static_data/npc_walker.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:include schemaLocation="import.xsd" />

	<xs:element name="npc_walker" type="Wlk" />

	<xs:complexType name="Wlk">
		<xs:sequence>
			<xs:element ref="import" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="walker_template" type="Wlk_Template" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="Wlk_Template">
		<xs:sequence>
			<xs:element name="routes" type="Routes" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="route_id" type="xs:int" use="required" />
	</xs:complexType>
	
	<xs:complexType name="Routes" >
		<xs:sequence>
			<xs:element name="routestep" type="RouteStep" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="RouteStep" >
		<xs:attribute name="step" type="xs:int" use="required" />
		<xs:attribute name="loc_x" type="xs:float" use="required" />
		<xs:attribute name="loc_y" type="xs:float" use="required" />
		<xs:attribute name="loc_z" type="xs:float" use="required" />
		<xs:attribute name="rest_time" type="xs:int" use="required" />
	</xs:complexType>

</xs:schema>

=== Sinien/aion-lightning-2/trunk/AL-Game/data/static_data/npc_walker.xml
<?xml version="1.0" encoding="UTF-8"?>
<npc_walker xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="npc_walker.xsd">
	<walker_template route_id="1">
		<routes>
			<routestep step="1" loc_x="1755.2654" loc_y="1401.5167" loc_z="575.83844" rest_time="0"/>
			<routestep step="2" loc_x="1768.111" loc_y="1398.0126" loc_z="578.6604" rest_time="0"/>
			<routestep step="3" loc_x="1795.2981" loc_y="1397.8864" loc_z="582.8908" rest_time="0"/>
			<routestep step="4" loc_x="1811.8364" loc_y="1397.8558" loc_z="583.08203" rest_time="0"/>
			<routestep step="5" loc_x="1840.5798" loc_y="1397.8303" loc_z="587.412" rest_time="0"/>
			<routestep step="6" loc_x="1857.4154" loc_y="1398.9735" loc_z="590.00977" rest_time="0"/>
			<routestep step="7" loc_x="1856.7184" loc_y="1409.2963" loc_z="590.01135" rest_time="0"/>
			<routestep step="8" loc_x="1827.8679" loc_y="1406.4335" loc_z="585.30066" rest_time="0"/>
			<routestep step="9" loc_x="1795.916" loc_y="1407.6373" loc_z="582.9019" rest_time="0"/>
			<routestep step="10" loc_x="1743.2365" loc_y="1407.4434" loc_z="572.85254" rest_time="0"/>
		</routes>
	</walker_template>
	<walker_template route_id="2">
		<routes>
			<routestep step="1" loc_x="387.10675" loc_y="1868.1742" loc_z="146.33006" rest_time="0"/>
			<routestep step="2" loc_x="378.67044" loc_y="1879.4595" loc_z="147.31555" rest_time="1"/>
			<routestep step="3" loc_x="363.31458" loc_y="1895.596" loc_z="149.74234" rest_time="0"/>
			<routestep step="4" loc_x="357.6157" loc_y="1911.3687" loc_z="151.7326" rest_time="2"/>
			<routestep step="5" loc_x="357.12106" loc_y="1929.354" loc_z="153.94952" rest_time="0"/>
			<routestep step="6" loc_x="359.27063" loc_y="1897.9075" loc_z="150.76773" rest_time="0"/>
			<routestep step="7" loc_x="381.40176" loc_y="1878.9325" loc_z="147.38745" rest_time="2"/>
		</routes>
	</walker_template>
	<walker_template route_id="3">
		<routes>
			<routestep step="1" loc_x="1193.0087" loc_y="1087.0784" loc_z="137.55869" rest_time="0"/>
			<routestep step="2" loc_x="1197.5963" loc_y="1089.4756" loc_z="138.07454" rest_time="0"/>
			<routestep step="3" loc_x="1189.9689" loc_y="1092.3396" loc_z="137.09988" rest_time="0"/>
			<routestep step="4" loc_x="1190.5154" loc_y="1080.7032" loc_z="137.30267" rest_time="0"/>
		</routes>
	</walker_template>
	<walker_template route_id="4">
		<routes>
			<routestep step="1" loc_x="1210.5848" loc_y="1083.4032" loc_z="138.75" rest_time="0"/>
			<routestep step="2" loc_x="1213.9358" loc_y="1091.1422" loc_z="139.36697" rest_time="0"/>
			<routestep step="3" loc_x="1203.0881" loc_y="1081.4152" loc_z="138.85455" rest_time="0"/>
			<routestep step="4" loc_x="1214.0228" loc_y="1073.7064" loc_z="138.875" rest_time="0"/>
		</routes>
	</walker_template>
	<walker_template route_id="5">
		<routes>
			<routestep step="1" loc_x="157.81361" loc_y="325.04657" loc_z="121.938736" rest_time="0"/>
			<routestep step="2" loc_x="157.8136" loc_y="325.04657" loc_z="121.938736" rest_time="0"/>
			<routestep step="3" loc_x="150.90173" loc_y="312.77682" loc_z="122.56312" rest_time="0"/>
		</routes>
	</walker_template>
	<walker_template route_id="6">
		<routes>
			<routestep step="1" loc_x="176.12648" loc_y="281.0444" loc_z="124.43186" rest_time="0"/>
			<routestep step="2" loc_x="176.12648" loc_y="281.0444" loc_z="124.43186" rest_time="0"/>
			<routestep step="3" loc_x="164.75258" loc_y="288.57532" loc_z="124.38446" rest_time="0"/>
		</routes>
	</walker_template>
	<walker_template route_id="7">
		<routes>
			<routestep step="1" loc_x="154.2884" loc_y="441.20123" loc_z="140.4" rest_time="0"/>
			<routestep step="2" loc_x="154.2884" loc_y="441.20123" loc_z="140.4" rest_time="0"/>
			<routestep step="3" loc_x="166.10286" loc_y="415.80978" loc_z="139.7" rest_time="0"/>
		</routes>
	</walker_template>
	<walker_template route_id="8">
		<routes>
			<routestep step="1" loc_x="179.2198" loc_y="378.4973" loc_z="144.1" rest_time="0"/>
			<routestep step="2" loc_x="176.8896" loc_y="383.7659" loc_z="144.2" rest_time="0"/>
			<routestep step="3" loc_x="174.966" loc_y="388.654" loc_z="144.1" rest_time="0"/>
		</routes>
	</walker_template>
	<walker_template route_id="9">
		<routes>
			<routestep step="1" loc_x="207.08524" loc_y="310.05295" loc_z="137.67357" rest_time="0"/>
			<routestep step="2" loc_x="202.88045" loc_y="321.026" loc_z="141.38757" rest_time="0"/>
			<routestep step="3" loc_x="198.94485" loc_y="333.553" loc_z="144.32677" rest_time="0"/>
		</routes>
	</walker_template>
	<walker_template route_id="10">
		<routes>
			<routestep step="1" loc_x="221.43166" loc_y="277.81894" loc_z="125.087" rest_time="0"/>
			<routestep step="2" loc_x="228.75233" loc_y="283.31805" loc_z="127.86175" rest_time="0"/>
			<routestep step="3" loc_x="217.84033" loc_y="269.5496" loc_z="121.873314" rest_time="0"/>
			<routestep step="4" loc_x="212.78696" loc_y="257.12015" loc_z="119.735275" rest_time="0"/>
		</routes>
	</walker_template>
	<walker_template route_id="11">
		<routes>
			<routestep step="1" loc_x="195.12996" loc_y="223.16008" loc_z="111.07573" rest_time="0"/>
			<routestep step="2" loc_x="204.85594" loc_y="227.87204" loc_z="113.25542" rest_time="0"/>
			<routestep step="3" loc_x="195.12996" loc_y="223.16008" loc_z="111.07573" rest_time="0"/>
			<routestep step="4" loc_x="195.39989" loc_y="210.87285" loc_z="109.17538" rest_time="0"/>
			<routestep step="5" loc_x="200.5981" loc_y="202.55867" loc_z="108.60568" rest_time="0"/>
		</routes>
	</walker_template>
	<walker_template route_id="12">
		<routes>
			<routestep step="1" loc_x="227.43016" loc_y="179.00151" loc_z="110.3" rest_time="0"/>
			<routestep step="2" loc_x="237.07484" loc_y="186.11015" loc_z="112.0" rest_time="0"/>
			<routestep step="3" loc_x="224.38875" loc_y="190.98651" loc_z="114.4" rest_time="0"/>
		</routes>
	</walker_template>
	<walker_template route_id="13">
		<routes>
			<routestep step="1" loc_x="272.46545" loc_y="201.89696" loc_z="119.234886" rest_time="0"/>
			<routestep step="2" loc_x="285.90567" loc_y="210.4403" loc_z="119.686676" rest_time="0"/>
			<routestep step="3" loc_x="285.26807" loc_y="231.48059" loc_z="119.11023" rest_time="0"/>
			<routestep step="4" loc_x="256.05463" loc_y="195.1985" loc_z="117.46713" rest_time="0"/>
			<routestep step="5" loc_x="224.38875" loc_y="190.98651" loc_z="114.34763" rest_time="0"/>
			<routestep step="6" loc_x="237.07484" loc_y="186.11015" loc_z="111.99673" rest_time="0"/>
			<routestep step="7" loc_x="221.89069" loc_y="183.74089" loc_z="108.97251" rest_time="0"/>
			<routestep step="8" loc_x="208.16281" loc_y="190.87318" loc_z="107.78945" rest_time="0"/>
			<routestep step="9" loc_x="195.39989" loc_y="210.87285" loc_z="109.17538" rest_time="0"/>
			<routestep step="10" loc_x="195.12996" loc_y="223.16008" loc_z="111.07573" rest_time="0"/>
			<routestep step="11" loc_x="222.29643" loc_y="257.04764" loc_z="120.30293" rest_time="0"/>
			<routestep step="12" loc_x="221.43166" loc_y="277.81894" loc_z="125.087" rest_time="0"/>
		</routes>
	</walker_template>
	<walker_template route_id="14">
		<routes>
			<routestep step="1" loc_x="329.0482" loc_y="141.81827" loc_z="125.376915" rest_time="0"/>
			<routestep step="2" loc_x="314.21796" loc_y="151.55272" loc_z="127.57385" rest_time="0"/>
			<routestep step="3" loc_x="308.08008" loc_y="157.1121" loc_z="126.7866" rest_time="0"/>
		</routes>
	</walker_template>
	<walker_template route_id="15">
		<routes>
			<routestep step="1" loc_x="410.95706" loc_y="103.03791" loc_z="116.10972" rest_time="0"/>
			<routestep step="2" loc_x="401.18141" loc_y="105.35983" loc_z="116.10972" rest_time="0"/>
			<routestep step="3" loc_x="379.7129" loc_y="117.554436" loc_z="116.110085" rest_time="0"/>
		</routes>
	</walker_template>
	<walker_template route_id="16">
		<routes>
			<routestep step="1" loc_x="398.77063" loc_y="78.767975" loc_z="117.19401" rest_time="0"/>
			<routestep step="2" loc_x="374.68747" loc_y="91.46251" loc_z="117.19436" rest_time="0"/>
			<routestep step="3" loc_x="365.03174" loc_y="98.55415" loc_z="117.19401" rest_time="0"/>
		</routes>
	</walker_template>
	<walker_template route_id="17">
		<routes>
			<routestep step="1" loc_x="648.6" loc_y="889.6" loc_z="103.6" rest_time="5"/>
			<routestep step="2" loc_x="648.9" loc_y="892.7" loc_z="103.6" rest_time="5"/>
			<routestep step="3" loc_x="652.5" loc_y="891.9" loc_z="103.6" rest_time="0"/>
			<routestep step="4" loc_x="653.8" loc_y="888.2" loc_z="103.6" rest_time="0"/>
			<routestep step="5" loc_x="651.3" loc_y="887.3" loc_z="103.6" rest_time="0"/>
		</routes>
	</walker_template>
	<walker_template route_id="18">
		<routes>
			<routestep step="1" loc_x="1288.9" loc_y="2172.6" loc_z="150.6" rest_time="0"/>
			<routestep step="2" loc_x="1323.3" loc_y="2184.3" loc_z="143.8" rest_time="0"/>
			<routestep step="3" loc_x="1316.0" loc_y="2209.2" loc_z="141.1" rest_time="0"/>
			<routestep step="4" loc_x="1309.2" loc_y="2244.6" loc_z="143.2" rest_time="0"/>
			<routestep step="5" loc_x="1317.4" loc_y="2248.3" loc_z="144.1" rest_time="0"/>
			<routestep step="6" loc_x="1337.0" loc_y="2235.1" loc_z="146.5" rest_time="0"/>
			<routestep step="7" loc_x="1341.09" loc_y="2239.32" loc_z="146.375" rest_time="0"/>
			<routestep step="8" loc_x="1336.43" loc_y="2243.032" loc_z="146.375" rest_time="0"/>
			<routestep step="9" loc_x="1330.1758" loc_y="2240.8223" loc_z="146.375" rest_time="0"/>
			<routestep step="10" loc_x="1313.0" loc_y="2253.9" loc_z="142.8" rest_time="0"/>
			<routestep step="11" loc_x="1312.2" loc_y="2265.2" loc_z="142.9" rest_time="0"/>
			<routestep step="12" loc_x="1304.8" loc_y="2272.9" loc_z="144.8" rest_time="0"/>
			<routestep step="13" loc_x="1275.1" loc_y="2274.2" loc_z="143.3" rest_time="0"/>
			<routestep step="14" loc_x="1258.3" loc_y="2252.2" loc_z="142.5" rest_time="0"/>
