=== Sinien/aion-lightning-2/trunk/AL-Game/data/static_data/npc_teleporter.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:include schemaLocation="import.xsd" />

	<xs:element name="npc_teleporter" type="Data" />

	<xs:complexType name="Data">
		<xs:sequence>
			<xs:element ref="import" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="teleporter_template" type="Template" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="Template">
		<xs:sequence>
			<xs:element name="locations" type="Locations" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="npc_id" type="xs:int" use="required" />
		<xs:attribute name="name" type="xs:string" use="required" />
		<xs:attribute name="teleportId" type="xs:int" use="required" />
		<xs:attribute name="type" type="TeleportType" use="required" />
	</xs:complexType>
	
	<xs:simpleType name="TeleportType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="FLIGHT" />
			<xs:enumeration value="REGULAR" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:complexType name="Locations" >
		<xs:sequence>
			<xs:element name="telelocation" type="TeleportLocation" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="TeleportLocation" >
		<xs:attribute name="loc_id" type="xs:int" use="required" />
		<xs:attribute name="teleportid" type="xs:int"/>
		<xs:attribute name="price" type="xs:int"/>
	</xs:complexType>

</xs:schema>

=== Sinien/aion-lightning-2/trunk/AL-Game/data/static_data/npc_teleporter.xml
<?xml version="1.0" encoding="UTF-8"?>
<npc_teleporter xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="npc_teleporter.xsd">
	<!-- 
		Here possible to define 2 types of teleporters: REGULAR and FLIGHT
		All of them have destination locations with different prices
		
		FLIGHT teleporters have:
		- loc_id
		- teleportid
		- price
		
		REGULAR teleporters have:
		-loc_id
		-price
		
		All loc_id should be defined in teleport_location.xml file
	 -->
	<!-- ASMODIANS -->
	<!-- Pandaemonium -->
	<teleporter_template npc_id="204191" name="Doman" teleportId="50" type="REGULAR">
		<locations>
			<telelocation loc_id="8" price="100"/>
			<telelocation loc_id="9" price="500"/>
			<telelocation loc_id="10" price="1500"/>
			<telelocation loc_id="11" price="2500"/>
			<telelocation loc_id="82" price="1400"/>
		</locations>
	</teleporter_template>
	<!-- Pandaemonium City Teleports -->
	<teleporter_template npc_id="730018" name="DC1_SPOT_Street" teleportId="202" type="REGULAR">
		<locations>
			<telelocation loc_id="33" price="200"/>
			<telelocation loc_id="106" price="800"/>
		</locations>
	</teleporter_template>
	<teleporter_template npc_id="730017" name="DC1_SPOT_Bridge" teleportId="201" type="REGULAR">
		<locations>
			<telelocation loc_id="34" price="200"/>
			<telelocation loc_id="106" price="800"/>
		</locations>
	</teleporter_template>
	<teleporter_template npc_id="730267" name="DC1_SPOT_Westside" teleportId="214" type="REGULAR">
		<locations>
			<telelocation loc_id="33" price="1000"/>
			<telelocation loc_id="34" price="800"/>
		</locations>
	</teleporter_template>
	<!-- Ishalgen -->
	<teleporter_template npc_id="203679" name="Osmar" teleportId="51" type="REGULAR">
		<locations>
			<telelocation loc_id="7" price="100"/>
			<telelocation loc_id="9" price="800"/>
		</locations>
	</teleporter_template>
	<teleporter_template npc_id="203513" name="Sheofin" teleportId="203" type="FLIGHT">
		<locations>
			<telelocation loc_id="18" teleportid="11001" price="200"/>
		</locations>
	</teleporter_template>
	<teleporter_template npc_id="203545" name="Garhara" teleportId="204" type="FLIGHT">
		<locations>
			<telelocation loc_id="17" teleportid="12001" price="200"/>
		</locations>
	</teleporter_template>
	<!-- Altgard -->
	<teleporter_template npc_id="203581" name="Ukin" teleportId="52" type="REGULAR">
		<locations>
			<telelocation loc_id="7" price="500"/>
			<telelocation loc_id="8" price="800"/>
			<telelocation loc_id="10" price="1700"/>
			<telelocation loc_id="11" price="2700"/>
			<telelocation loc_id="82" price="1600"/>
		</locations>
	</teleporter_template>
	<teleporter_template npc_id="203561" name="Lenat" teleportId="205" type="FLIGHT">
		<locations>
			<telelocation loc_id="32" teleportid="15001" price="500"/>
			<telelocation loc_id="20" teleportid="13001" price="700"/>
			<telelocation loc_id="121" teleportid="124001" price="400"/>
			<telelocation loc_id="122" teleportid="126001" price="250"/>
		</locations>
	</teleporter_template>
	<teleporter_template npc_id="203678" name="Latunin" teleportId="206" type="FLIGHT">
		<locations>
			<telelocation loc_id="19" teleportid="14001" price="700"/>
		</locations>
	</teleporter_template>
	<teleporter_template npc_id="203683" name="Rubander" teleportId="207" type="FLIGHT">
		<locations>
			<telelocation loc_id="19" teleportid="16001" price="500"/>
		</locations>
	</teleporter_template>
	<teleporter_template npc_id="798448" name="Petesson" teleportId="218" type="FLIGHT">
		<locations>
			<telelocation loc_id="19" teleportid="125001" price="400"/>
		</locations>
	</teleporter_template>
	<teleporter_template npc_id="798449" name="Lemel" teleportId="219" type="FLIGHT">
		<locations>
			<telelocation loc_id="19" teleportid="127001" price="250"/>
		</locations>
	</teleporter_template>
	<!-- Morheim -->
	<teleporter_template npc_id="204399" name="Orhe" teleportId="53" type="REGULAR">
		<locations>
			<telelocation loc_id="7" price="1500"/>
			<telelocation loc_id="9" price="1700"/>
			<telelocation loc_id="82" price="2000"/>
			<telelocation loc_id="11" price="3200"/>
		</locations>
	</teleporter_template>
	<teleporter_template npc_id="204319" name="Yornduf" teleportId="208" type="FLIGHT">
		<locations>
			<telelocation loc_id="65" teleportid="25001" price="1600"/>
			<telelocation loc_id="64" teleportid="24001" price="1000"/>
			<telelocation loc_id="123" teleportid="128001" price="880"/>
		</locations>
	</teleporter_template>
	<teleporter_template npc_id="204334" name="Grander" teleportId="209" type="FLIGHT">
		<locations>
			<telelocation loc_id="63" teleportid="26001" price="1000"/>
			<telelocation loc_id="65" teleportid="27001" price="1800"/>
			<telelocation loc_id="124" teleportid="130001" price="1000"/>
		</locations>
	</teleporter_template>
	<teleporter_template npc_id="204358" name="Kiril" teleportId="210" type="FLIGHT">
		<locations>
			<telelocation loc_id="63" teleportid="28001" price="1600"/>
			<telelocation loc_id="64" teleportid="29001" price="1800"/>
			<telelocation loc_id="125" teleportid="132001" price="1200"/>
			<telelocation loc_id="126" teleportid="134001" price="1200"/>
		</locations>
	</teleporter_template>
	<teleporter_template npc_id="798450" name="Severin" teleportId="220" type="FLIGHT">
		<locations>
			<telelocation loc_id="63" teleportid="129001" price="880"/>
		</locations>
	</teleporter_template>
	<teleporter_template npc_id="798451" name="Severin" teleportId="221" type="FLIGHT">
		<locations>
			<telelocation loc_id="64" teleportid="131001" price="1000"/>
		</locations>
	</teleporter_template>
	<teleporter_template npc_id="798452" name="Belhaven" teleportId="222" type="FLIGHT">
		<locations>
			<telelocation loc_id="65" teleportid="133001" price="1200"/>
		</locations>
	</teleporter_template>
	<teleporter_template npc_id="798453" name="Olav" teleportId="223" type="FLIGHT">
		<locations>
			<telelocation loc_id="65" teleportid="135001" price="1200"/>
		</locations>
	</teleporter_template>
	<!-- Beluslan -->
	<!-- player spawn are not in front of teleporters, search and you will find teleporters -->
	<teleporter_template npc_id="204724" name="Eda" teleportId="55" type="REGULAR">
		<locations>
			<telelocation loc_id="7" price="100"/>
			<telelocation loc_id="9" price="500"/>
			<telelocation loc_id="10" price="1500"/>
			<telelocation loc_id="82" price="1400"/>
		</locations>
	</teleporter_template>
	<teleporter_template npc_id="204718" name="Gylfi" teleportId="211" type="FLIGHT">
		<locations>
			<telelocation loc_id="79" teleportid="48001" price="1400"/>
			<telelocation loc_id="80" teleportid="50001" price="1900"/>
			<telelocation loc_id="129" teleportid="108001" price="700"/>
		</locations>
	</teleporter_template>
	<teleporter_template npc_id="204747" name="Kunbernan" teleportId="212" type="FLIGHT">
		<locations>
			<telelocation loc_id="78" teleportid="49001" price="1400"/>
			<telelocation loc_id="80" teleportid="52001" price="2100"/>
		</locations>
	</teleporter_template>
	<teleporter_template npc_id="204756" name="Boudica" teleportId="213" type="FLIGHT">
		<locations>
			<telelocation loc_id="78" teleportid="51001" price="1900"/>
			<telelocation loc_id="79" teleportid="53001" price="2100"/>
			<telelocation loc_id="130" teleportid="110001" price="1000"/>
			<telelocation loc_id="131" teleportid="112001" price="1100"/>
		</locations>
	</teleporter_template>
	<teleporter_template npc_id="798456" name="Suomi" teleportId="226" type="FLIGHT">
		<locations>
			<telelocation loc_id="78" teleportid="109001" price="700"/>
		</locations>
	</teleporter_template>
	<teleporter_template npc_id="798457" name="Berta" teleportId="227" type="FLIGHT">
		<locations>
			<telelocation loc_id="80" teleportid="111001" price="1000"/>
		</locations>
	</teleporter_template>
	<teleporter_template npc_id="798458" name="Konradin" teleportId="228" type="FLIGHT">
		<locations>
			<telelocation loc_id="80" teleportid="113001" price="1100"/>
		</locations>
	</teleporter_template>
	<!-- Brusthonin -->
	<teleporter_template npc_id="205124" name="Tusen" teleportId="54" type="REGULAR">
		<locations>
			<telelocation loc_id="7" price="1400"/>
			<telelocation loc_id="9" price="1600"/>
			<telelocation loc_id="10" price="2000"/>
			<telelocation loc_id="11" price="2900"/>
		</locations>
	</teleporter_template>
	<teleporter_template npc_id="205207" name="Ullur" teleportId="609" type="FLIGHT">
		<locations>
			<telelocation loc_id="87" teleportid="65001" price="2300"/>
			<telelocation loc_id="88" teleportid="70001" price="2900"/>
		</locations>
	</teleporter_template>
	<teleporter_template npc_id="205145" name="Billeten" teleportId="610" type="FLIGHT">
		<locations>
			<telelocation loc_id="86" teleportid="66001" price="2300"/>
			<telelocation loc_id="88" teleportid="67001" price="3300"/>
		</locations>
	</teleporter_template>
	<teleporter_template npc_id="205174" name="Svan" teleportId="611" type="FLIGHT">
		<locations>
			<telelocation loc_id="86" teleportid="69001" price="2900"/>
			<telelocation loc_id="87" teleportid="68001" price="3300"/>
		</locations>
	</teleporter_template>
	<!-- ELYOS -->
	<!-- Poeta -->
	<teleporter_template npc_id="203194" name="Daines" teleportId="2" type="REGULAR">
		<locations>
			<telelocation loc_id="2" price="100"/>
			<telelocation loc_id="4" price="800"/>
		</locations>
	</teleporter_template>
	<teleporter_template npc_id="203070" name="Kustanon" teleportId="103" type="FLIGHT">
		<locations>
			<telelocation loc_id="13" teleportid="5001" price="200"/>
		</locations>
	</teleporter_template>
	<teleporter_template npc_id="203083" name="Aero" teleportId="104" type="FLIGHT">
		<locations>
			<telelocation loc_id="12" teleportid="6001" price="200"/>
		</locations>
