=== Sinien/aion-lightning-2/trunk/AL-Game/data/static_data/portals/portal_templates.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:include schemaLocation="../import.xsd" />
	<xs:include schemaLocation="../global_types.xsd" />

	<xs:element name="portal_templates">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="import" minOccurs="0" maxOccurs="unbounded" />
				<xs:element name="portal" type="Portal" minOccurs="0"
					maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="Portal">
		<xs:sequence>
			<xs:element name="entrypoint" type="EntryPoint" minOccurs="0"
				maxOccurs="2" />
			<xs:element name="exitpoint" type="ExitPoint" minOccurs="1"
				maxOccurs="1" />
			<xs:element name="portalitem" type="PortalItem" minOccurs="0"
				maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="race" type="Race" />
		<xs:attribute name="group" type="xs:boolean" />
		<xs:attribute name="maxlevel" type="xs:int" />
		<xs:attribute name="minlevel" type="xs:int" />
		<xs:attribute name="instance" type="xs:boolean" />
		<xs:attribute name="name" type="xs:string" />
		<xs:attribute name="npcid" type="xs:int" />
		<xs:attribute name="titleid" type="xs:int" />		
	</xs:complexType>

	<xs:complexType name="EntryPoint">
		<xs:attribute name="mapid" type="xs:int" />
		<xs:attribute name="x" type="xs:float" />
		<xs:attribute name="y" type="xs:float" />
		<xs:attribute name="z" type="xs:float" />
		<xs:attribute name="race" type="Race" />
	</xs:complexType>

	<xs:complexType name="ExitPoint">
		<xs:attribute name="mapid" type="xs:int" />
		<xs:attribute name="x" type="xs:float" />
		<xs:attribute name="y" type="xs:float" />
		<xs:attribute name="z" type="xs:float" />
	</xs:complexType>

	<xs:complexType name="PortalItem">
		<xs:attribute name="id" type="xs:int" />
		<xs:attribute name="itemid" type="xs:int" />
		<xs:attribute name="quantity" type="xs:int" />
	</xs:complexType>
	
</xs:schema>

=== Sinien/aion-lightning-2/trunk/AL-Game/data/static_data/portals/portal_templates.xml
<?xml version="1.0" encoding="UTF-8"?>
<portal_templates xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="portal_templates.xsd">
	<!-- INSTANCES -->
	<!-- Adma Stronghold -->
	<portal npcid="730165" instance="true" minlevel="50" maxlevel="50" group="true">
		<entrypoint mapid="220050000" x="2339.747" y="160.00119" z="246.44734"/>
		<exitpoint mapid="320130000" x="450.66864" y="199.70248" z="167.84444"/>
	</portal>
	<!-- Sulfur tree nest -->
	<portal npcid="700452" instance="true" minlevel="35" maxlevel="50" group="true">
		<entrypoint mapid="400010000" x="1344.07" y="1243.71" z="1498.31"/>
		<exitpoint mapid="300060000" x="462.352" y="345.609" z="162.817"/>
	</portal>
	<!-- Asteria chamber -->
	<portal npcid="700460" instance="true" minlevel="45" maxlevel="50" group="true">
		<entrypoint mapid="400010000" x="705.45" y="2921.74" z="2880.84"/>
		<exitpoint mapid="300050000" x="469.343" y="567.713" z="201.732"/>
	</portal>
	<!-- Aetherogenetics Lab -->
	<portal npcid="730034" instance="true" minlevel="41" maxlevel="50" group="true">
		<entrypoint mapid="210040000" x="233.95" y="533.53" z="158.75"/>
		<exitpoint mapid="310050000" x="348.7295" y="235.60219" z="147.67067"/>
	</portal>
	<!-- Left Wing Chamber  -->
	<portal npcid="700454" instance="true" minlevel="35" maxlevel="50" group="true">
		<entrypoint mapid="400010000" x="2784.99" y="2664.03" z="1486.7"/>
		<exitpoint mapid="300080000" x="672.09576" y="606.1819" z="321.19"/>
	</portal>
	<!--Chamber of Roah -->
	<portal npcid="700479" instance="true" minlevel="40" maxlevel="50" group="true">
		<entrypoint mapid="400010000" x="2712.53" y="757.89" z="2854.295"/>
		<exitpoint mapid="300070000" x="503.74" y="395.70" z="94.34"/>
	</portal>
	<!-- Alquimia Research Center Entrance -->
	<portal npcid="730110" instance="true" minlevel="41" maxlevel="50" group="true">
		<entrypoint mapid="220040000" x="2203.19" y="2923.57" z="699.81"/>
		<exitpoint mapid="320110000" x="602.62976" y="526.6474" z="200.05792"/>
	</portal>
	<!-- Nochsana Training Camp Asmodians -->
	<portal npcid="700414" instance="true" minlevel="25" maxlevel="28" group="true" race="ASMODIANS">
		<entrypoint mapid="400010000" x="876.7211" y="3079.2874" z="1644.5786" race="ASMODIANS"/>
		<exitpoint mapid="300030000" x="513" y="668" z="331"/>
	</portal>
	<!-- Nochsana Training Camp Elyos -->
	<portal npcid="700413" instance="true" minlevel="25" maxlevel="28" group="true" race="ELYOS">
		<entrypoint mapid="400010000" x="2890" y="754" z="1498.5786" race="ELYOS"/>
		<exitpoint mapid="300030000" x="513" y="668" z="331"/>
	</portal>
	<!-- Fire Temple-->
	<portal npcid="730047" instance="true" minlevel="30" group="true" maxlevel="50">
		<entrypoint mapid="220020000" x="1592.178" y="977.2572" z="140.75" race="ASMODIANS"/>
		<entrypoint mapid="210020000" x="1343.28" y="350.96" z="348.67" race="ELYOS"/>
		<exitpoint mapid="320100000" x="148.256" y="460.857" z="141.713"/>
	</portal>
	<!-- Draupnir Cave Entrance -->
	<portal npcid="700370" instance="true" minlevel="44" maxlevel="50" group="true">
		<entrypoint mapid="220040000" x="1605.27" y="2729.9" z="705.345"/>
		<exitpoint mapid="320080000" x="491" y="373" z="622"/>
	</portal>
	<!-- Alukina's Palace Entrance -->
	<portal npcid="730137" instance="false" minlevel="38" maxlevel="50" group="false">
		<entrypoint mapid="220040000" x="576.73724" y="2503.9868" z="290.09546"/>
		<exitpoint mapid="220040000" x="593" y="2535" z="289"/>
	</portal>
	<!-- Alukina's Palace Exit -->
	<portal npcid="730138" instance="false" minlevel="38" maxlevel="50" group="false">
		<entrypoint mapid="220040000" x="589.1326" y="2534.8586" z="288.48273"/>
		<exitpoint mapid="220040000" x="571" y="2504" z="289"/>
	</portal>
	<!-- Artifact of Circulation / DarkPoeta -->
	<portal npcid="730185" instance="true" minlevel="50" maxlevel="50" group="true" race="ASMODIANS">
		<entrypoint mapid="220040000" x="2420.12" y="2061.31" z="579.7" race="ASMODIANS"/>
		<exitpoint mapid="300040000" x="1214" y="412" z="140"/>
		<portalitem id="1" itemid="186000048" quantity="20"/>
		<portalitem id="2" itemid="186000050" quantity="1"/>
	</portal>
	<!-- Artifact of Transcendence / DarkPoeta -->
	<portal npcid="730186" instance="true" minlevel="50" maxlevel="50" group="true" race="ELYOS">
		<entrypoint mapid="210040000" x="2019.51" y="1467.34" z="127.19" race="ELYOS"/>
		<exitpoint mapid="300040000" x="1214" y="412" z="140"/>
		<portalitem id="1" itemid="186000048" quantity="20"/>
		<portalitem id="2" itemid="186000050" quantity="1"/>
	</portal>
	<!-- Artifact of Time / DarkPoeta -->
	<portal npcid="730215" instance="true" minlevel="50" maxlevel="50" group="true">
		<entrypoint mapid="400010000" x="2158" y="1581" z="2272.5"/>
		<exitpoint mapid="300040000" x="1214" y="412" z="140"/>
		<portalitem id="1" itemid="186000048" quantity="5"/>
		<portalitem id="2" itemid="186000050" quantity="1"/>
	</portal>
	<!-- Sky Temple Interior / Water Room Entrance-->
	<portal npcid="730041" instance="true" minlevel="27" maxlevel="50" group="true">
		<entrypoint mapid="220020000" x="1673.5468" y="1147.3054" z="200.42954"/>
		<exitpoint mapid="320050000" x="473.72284" y="115.55677" z="214.81421"/>
	</portal>
	<!-- Sky Temple Interior / Water Room Exit-->
	<portal npcid="730042" instance="false" minlevel="27" maxlevel="50" group="false">
		<entrypoint mapid="320050000" x="380.75192" y="73.82643" z="226.6414"/>
		<exitpoint mapid="220020000" x="1663" y="1145" z="200"/>
	</portal>
	<!-- Sky Temple Interior / Wind Room Entrance-->
	<portal npcid="730043" instance="true" minlevel="27" maxlevel="50" group="true">
		<entrypoint mapid="220020000" x="1684.3113" y="1155.8898" z="200.3536"/>
		<exitpoint mapid="320050000" x="308.1934" y="434.4128" z="416.82278"/>
	</portal>
	<!-- Sky Temple Interior / Wind Room Exit-->
	<portal npcid="730044" instance="false" minlevel="27" maxlevel="50" group="false">
		<entrypoint mapid="320050000" x="460.03848" y="437.17206" z="375.05527"/>
		<exitpoint mapid="220020000" x="1686" y="1160" z="200"/>
	</portal>
	<!-- Sky Temple Interior / Fire Room Entrance-->
	<portal npcid="730045" instance="true" minlevel="27" maxlevel="50" group="true">
		<entrypoint mapid="220020000" x="1686.6586" y="1142.5929" z="200.3536"/>
		<exitpoint mapid="320050000" x="101.47154" y="23.524532" z="611.0359"/>
	</portal>
	<!-- Sky Temple Interior / Fire Room Exit-->
	<portal npcid="730046" instance="false" minlevel="27" maxlevel="50" group="false">
		<entrypoint mapid="320050000" x="228.15353" y="300.09668" z="550.68805"/>
		<exitpoint mapid="220020000" x="1695" y="1139" z="200"/>
	</portal>
	<!-- Azoturan Fortress -->
	<portal npcid="700364" instance="true" minlevel="43" maxlevel="50" group="true">
		<entrypoint mapid="210040000" x="542.84" y="712.9" z="153.03"/>
		<exitpoint mapid="310100000" x="304.16013" y="323.43713" z="1021.4955"/>
	</portal>
	<!-- Theobomos Lab -->
	<portal npcid="730154" instance="true" minlevel="50" maxlevel="50" group="true">
		<entrypoint mapid="210060000" x="2974.363" y="196.73184" z="170.99928"/>
		<exitpoint mapid="310110000" x="476.96606" y="201.32736" z="169.98848"/>
	</portal>
	<!-- Krotan Chamber -->
	<portal npcid="700458" instance="true" minlevel="45" maxlevel="50" group="true">
		<entrypoint mapid="400010000" x="2011.16" y="1252.53" z="2945.4082"/>
		<exitpoint mapid="300140000" x="527.79846" y="109.320755" z="175.92393"/>
	</portal>
	<!-- Tahabata Abyss Gate -->
	<portal npcid="730211" instance="true" minlevel="49" maxlevel="50" group="true">
		<entrypoint mapid="300040000" x="1179" y="1223" z="145"/>
		<exitpoint mapid="300040000" x="1188.80707" y="1241.4151" z="143.85065"/>
	</portal>
	<!-- QUEST PORTALS -->
	<!-- Pernos [Ascension quest] Elyos -->
	<portal npcid="790001" instance="true" race="ELYOS">
		<entrypoint mapid="210010000" x="241.094" y="1639.461" z="100.38" race="ELYOS"/>
		<exitpoint mapid="310010000" x="52" y="174" z="229"/>
	</portal>
	<!-- Munin [Ascension quest] Asmodians -->
	<portal npcid="203550" instance="true" race="ASMODIANS">
		<entrypoint mapid="220010000" x="378.9" y="1895.39" z="330.0" race="ASMODIANS"/>
		<exitpoint mapid="320010000" x="457.65" y="426.8" z="230.4"/>
	</portal>
	<!-- Morai [A Sliver of Darkness quest] Elyos -->
	<portal npcid="203164" instance="true" race="ELYOS">
		<entrypoint mapid="210030000" x="2315.9" y="1800" z="195.2" race="ELYOS"/>
		<exitpoint mapid="310070000" x="338" y="101" z="1191"/>
	</portal>
	<!-- Morai [No Escaping Destiny quest] Asmodians -->
	<portal npcid="203546" instance="true" race="ASMODIANS">
		<entrypoint mapid="220010000" x="1111.6" y="1716.6" z="270.6" race="ASMODIANS"/>
		<exitpoint mapid="320070000" x="257.5292" y="245" z="129"/>
	</portal>
	<!-- Statue of Mau Hero In [The Hand Behind The IceClaw] Asmodians -->
	<portal npcid="730052" minlevel="20" maxlevel="50" instance="false" titleid="58" race="ASMODIANS">
		<entrypoint mapid="220020000" x="0" y="0" z="0" race="ASMODIANS"/>
		<exitpoint mapid="220020000" x="1252.9" y="266" z="534.2"/>
	</portal>
	<!-- Statue of Mau Hero Out [The Hand Behind The IceClaw] Asmodians -->
	<portal npcid="730053" minlevel="20" maxlevel="50" instance="false" titleid="58" race="ASMODIANS">
		<entrypoint mapid="220020000" x="0" y="0" z="0" race="ASMODIANS"/>
		<exitpoint mapid="220020000" x="1243.5" y="263.9" z="531.3"/>
	</portal>
	<!-- ABYSS GATES -->
	<!-- Verteron to Abyss -->
	<portal npcid="700088" minlevel="25" maxlevel="50" instance="false" group="false" race="ELYOS">
		<entrypoint mapid="210030000" x="0" y="0" z="0" race="ELYOS"/>
		<exitpoint mapid="400010000" x="2867" y="1036" z="1528"/>
	</portal>
	<!-- Eltnen to Abyss -->
	<portal npcid="700177" minlevel="25" maxlevel="50" instance="false" group="false" race="ELYOS">
