=== Sinien/aion-lightning-2/trunk/tools/AL-PacketSamurai/dist/protocols/al-game_2.0.0.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:complexType name="T7_switch">
		<xs:sequence>
			<xs:element name="case" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="part" minOccurs="0" maxOccurs="unbounded">
							<xs:complexType>
								<xs:attribute name="type" use="required" type="xs:string"/>
								<xs:attribute name="name" use="required" type="xs:string"/>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
					<xs:attribute name="id" use="required" type="xs:string"/>
					<xs:attribute name="comment" use="required" type="xs:string"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="id" use="required" type="xs:byte"/>
	</xs:complexType>
	<xs:complexType name="T7_part">
		<xs:sequence>
			<xs:element name="reader" minOccurs="0">
				<xs:complexType>
					<xs:attribute name="type" use="required" type="xs:string"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="type" use="required" type="xs:string"/>
		<xs:attribute name="sizeid" type="xs:byte"/>
		<xs:attribute name="size" type="xs:byte"/>
		<xs:attribute name="name" use="required" type="xs:string"/>
		<xs:attribute name="id" type="xs:byte"/>
	</xs:complexType>
	<xs:complexType name="T4_switch">
		<xs:sequence>
			<xs:element name="case" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence minOccurs="0">
						<xs:element name="part" maxOccurs="unbounded">
							<xs:complexType>
								<xs:attribute name="type" use="required" type="xs:string"/>
								<xs:attribute name="name" use="required" type="xs:string"/>
								<xs:attribute name="id" type="xs:byte"/>
							</xs:complexType>
						</xs:element>
						<xs:element name="for" minOccurs="0">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="part" maxOccurs="unbounded">
										<xs:complexType>
											<xs:attribute name="type" use="required" type="xs:string"/>
											<xs:attribute name="name" use="required" type="xs:string"/>
										</xs:complexType>
									</xs:element>
								</xs:sequence>
								<xs:attribute name="id" use="required" type="xs:byte"/>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
					<xs:attribute name="id" use="required" type="xs:string"/>
					<xs:attribute name="comment" type="xs:string"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="id" use="required" type="xs:byte"/>
	</xs:complexType>
	<xs:complexType name="T4_part">
		<xs:sequence>
			<xs:element name="reader" minOccurs="0">
				<xs:complexType>
					<xs:attribute name="type" use="required" type="xs:string"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="type" use="required" type="xs:string"/>
		<xs:attribute name="sizeid" type="xs:byte"/>
		<xs:attribute name="size" type="xs:byte"/>
		<xs:attribute name="name" use="required" type="xs:string"/>
		<xs:attribute name="id" type="xs:byte"/>
	</xs:complexType>
	<xs:complexType name="T4_for">
		<xs:sequence>
			<xs:element name="part" maxOccurs="unbounded" type="T7_part"/>
			<xs:sequence minOccurs="0">
				<xs:element name="switch" type="T7_switch"/>
				<xs:element name="part" maxOccurs="unbounded" type="T7_part"/>
				<xs:element name="switch" type="T7_switch"/>
			</xs:sequence>
		</xs:sequence>
		<xs:attribute name="id" use="required" type="xs:byte"/>
	</xs:complexType>
	<xs:element name="protocol">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="packetfamilly" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="packet" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence minOccurs="0">
										<xs:element name="part" maxOccurs="unbounded" type="T4_part"/>
										<xs:choice minOccurs="0">
											<xs:sequence>
												<xs:element name="switch" type="T4_switch"/>
												<xs:sequence minOccurs="0">
													<xs:element name="part" maxOccurs="unbounded" type="T4_part"/>
													<xs:sequence minOccurs="0">
														<xs:sequence minOccurs="0">
															<xs:element name="switch" type="T4_switch"/>
															<xs:element name="part" type="T4_part"/>
														</xs:sequence>
														<xs:element name="for" type="T4_for"/>
													</xs:sequence>
												</xs:sequence>
											</xs:sequence>
											<xs:sequence>
												<xs:element name="for" type="T4_for"/>
												<xs:sequence minOccurs="0">
													<xs:element name="part" maxOccurs="unbounded" type="T4_part"/>
													<xs:choice minOccurs="0">
														<xs:element name="for" type="T4_for"/>
														<xs:element name="switch" type="T4_switch"/>
													</xs:choice>
												</xs:sequence>
											</xs:sequence>
										</xs:choice>
									</xs:sequence>
									<xs:attribute name="name" use="required" type="xs:string"/>
									<xs:attribute name="id" use="required" type="xs:string"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="way" use="required" type="xs:string"/>
						<xs:attribute name="switchtype" use="required" type="xs:string"/>
						<xs:attribute name="name" type="xs:string"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="strictlength" use="required" type="xs:boolean"/>
			<xs:attribute name="sizebytes" use="required" type="xs:byte"/>
			<xs:attribute name="port" use="required" type="xs:short"/>
			<xs:attribute name="name" use="required" type="xs:string"/>
			<xs:attribute name="crypt" use="required" type="xs:string"/>
			<xs:attribute name="checksumSize" use="required" type="xs:byte"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Sinien/aion-lightning-2/trunk/tools/AL-PacketSamurai/dist/protocols/al-game_2.0.0.0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited by Magenik -->
<protocol crypt="AionGame" name="al-game_2.0.0.0" port="7777" sizebytes="2" checksumSize="2" strictlength="false" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="al-game_2.0.0.0.xsd">
	<packetfamilly switchtype="c" way="ServerPackets" name="Server Messages">
		<packet id="0x00" name="SM_STATUPDATE_MP">
			<part name="currentMp" type="d"/>
			<part name="maxMp" type="d"/>
		</packet>
		<packet id="0x01" name="SM_STATUPDATE_HP">
			<part name="currentHp" type="d"/>
			<part name="maxHp" type="d"/>
		</packet>
		<packet id="0x3" name="SM_CHANNEL_INFO">
			<part name="currentChannel" type="d"/>
			<part name="instanceCount" type="d"/>
		</packet>
		<packet id="0x4" name="SM_MACRO_RESULT">
			<part name="result" type="c"/>
		</packet>
		<packet id="0x5" name="SM_MACRO_LIST">
			<part name="player objId" type="d"/>
			<part name="unk==1" type="c"/>
			<part id="0" name="size (inversed)" type="h"/>
			<for id="0">
				<part name="order" type="c"/>
				<part name="xml" type="S"/>
			</for>
		</packet>
		<packet id="0x6" name="SM_CHAT_INIT"/>
		<packet id="0x7" name="SM_NICKNAME_CHECK_RESPONSE">
			<part name="result" type="c"/>
		</packet>
		<packet id="0x08" name="SM_RIFT_ANNOUNCE">
			<part name="unk" type="d"/>
			<part name="unk" type="d"/>
			<part name="unk" type="d"/>
		</packet>
		<packet id="0x9" name="SM_SET_BIND_POINT">
			<part name="unk" type="c"/>
			<part name="unk" type="c"/>
			<part name="map id" type="d"/>
			<part name="x" type="f"/>
			<part name="y" type="f"/>
			<part name="z" type="f"/>
			<part name="unk" type="d"/>
		</packet>
		<packet id="0x0b" name="SM_ABYSS_RANK">
			<part name="ap" type="Q"/>
			<part name="rank" type="d"/>
			<part name="rating" type="d"/>
			<part name="next rank" type="d"/>
			<part name="all kill" type="d"/>
			<part name="max rank" type="d"/>
			<part name="day kill" type="d"/>
			<part name="day ap" type="Q"/>
			<part name="this week kill" type="d"/>
			<part name="this week ap" type="Q"/>
			<part name="last week kill" type="d"/>
			<part name="last week ap" type="Q"/>
			<part name="unk" type="c"/>
		</packet>
		<packet id="0x0c" name="SM_FRIEND_UPDATE">
			<part name="name" type="S"/>
			<part name="level" type="d"/>
			<part name="classID" type="d"/>
			<part name="isOnline" type="c"/>
			<part name="mapId" type="d"/>
			<part name="lastOnlineTime" type="d"/>
			<part name="note" type="S"/>
			<part name="statusIntValue" type="c"/>
		</packet>
		<packet id="0x0f" name="SM_LEARN_RECIPE">
			<part name="recipeId" type="d"/>
		</packet>
		<packet id="0x10" name="SM_FLY_TIME">
			<part name="currentFp" type="d"/>
			<part name="maxFp" type="d"/>
		</packet>
		<packet id="0x11" name="SM_TO_DO_WITH_ABYSS_LOG_9417947">
			<part name="artifactId" type="d"/>
			<part name="unk 0 ? 1" type="c"/>
		</packet>
		<packet id="0x12" name="SM_DELETE">
			<part name="objId" type="d"/>
			<part name="deleteTime" type="c"/>
		</packet>
		<packet id="0x14" name="SM_MESSAGE">
			<part id="0" name="chat type" type="c"/>
			<part name="can read" type="c"/>
			<part name="sender objId" type="d"/>
			<switch id="0">
				<case id="0">
					<part name="unk" type="h"/>
					<part name="message" type="S"/>
				</case>
				<case id="3">
					<part name="name" type="S"/>
					<part name="message" type="S"/>
					<part name="x" type="f"/>
					<part name="y" type="f"/>
					<part name="z" type="f"/>
				</case>
				<case id="4">
					<part name="name" type="S"/>
					<part name="message" type="S"/>
				</case>
				<case id="5">
					<part name="name" type="S"/>
					<part name="message" type="S"/>
				</case>
				<case id="7">
					<part name="name" type="S"/>
					<part name="message" type="S"/>
				</case>
				<case id="8">
					<part name="name" type="S"/>
					<part name="message" type="S"/>
				</case>
				<case id="24">
					<part name="unk" type="h"/>
					<part name="message" type="S"/>
				</case>
				<case id="30">
					<part name="unk" type="h"/>
					<part name="message" type="S"/>
				</case>
				<case id="28">
					<part name="unk" type="h"/>
					<part name="message" type="S"/>
				</case>
				<case id="32">
					<part name="unk" type="h"/>
					<part name="message" type="S"/>
				</case>
				<case id="33">
					<part name="unk" type="h"/>
					<part name="message" type="S"/>
				</case>
			</switch>
		</packet>
		<packet id="0x16" name="SM_INVENTORY_INFO">
			<part name="hide?" type="d"/>
			<part id="0" name="items" type="h"/>
			<for id="0">
				<part name="objId?" type="d"/>
				<part name="itemId" type="d"/>
				<part name="unk1" type="d"/>
				<part name="unk2" type="d"/>
				<part id="1" name="size" type="c"/>
				<part name="unk" sizeid="1" type="b"/>
				<part name="unk" type="d"/>
			</for>
		</packet>
		<packet id="0x17" name="SM_SYSTEM_MESSAGE">
			<part name="0x13" type="h"/>
			<part name="0x00" type="d"/>
			<part id="0" name="code" type="d"/>
			<switch id="0">
				<case id="230038" comment="CURRENT_LOCATION"/>
				<case id="900847" comment="BUDDYLIST_BUSY"/>
				<case id="1300627" comment="PLAYER_IS_OFFLINE"/>
				<case id="1300719" comment="REMAINING_PLAYING_TIME"/>
				<case id="1340000" comment="DIE"/>
				<case id="1300738" comment="REVIVE"/>
				<case id="1370002" comment="EXP"/>
				<case id="1300887" comment="BUDDYLIST_NOT_IN_LIST"/>
				<case id="1300891" comment="BLOCKLIST_NO_BUDDY"/>
				<case id="1300894" comment="BLOCKLIST_ALREADY_BLOCKED"/>
				<case id="1300897" comment="BLOCKLIST_NOT_BLOCKED"/>
				<case id="1301065" comment="DUEL_ASKED_BY"/>
				<case id="1301067" comment="DUEL_ASKED_BY_REJECTED [?]"/>
				<case id="1300094" comment="DUEL_ASKED_TO"/>
				<case id="1300097" comment="DUEL_ASKED_TO_REJECTED"/>
				<case id="1300628" comment="YOU_ARE_BLOCKED_BY"/>
				<case id="1390141" comment="ACCUMULATED_TIME"/>
				<case id="1370000" comment="UNKNOWN_1370000"/>
				<case id="default" comment="UNKNOWN"/>
			</switch>
			<part id="1" name="count" type="c"/>
			<for id="1">
				<part name="txt" type="S"/>
			</for>
		</packet>
		<packet id="0x18" name="SM_DELETE_ITEM">
			<part name="itemUniqueId" type="d"/>
			<part name="unk" type="c"/>
		</packet>
		<packet id="0x19" name="SM_INVENTORY_UPDATE">
			<part name="unk" type="h"/>
			<part name="itemCount" type="h"/>
		</packet>
		<packet id="0x1a" name="SM_UI_SETTINGS">
			<part name="settingsType" type="h"/>
			<part name="unk[0x1C]" type="c"/>
			<part name="data" type="b"/>
		</packet>
		<packet id="0x1B" name="SM_UPDATE_ITEM">
			<part name="uniqueId" type="d"/>
			<part name="unk[0x24]" type="h"/>
			<part name="itemNameId" type="d"/>
			<part name="unk[0]" type="h"/>
			<part id="0" name="itemDetailsLength" type="h"/>
			<part name="itemDetails" sizeid="0" type="b"/>
		</packet>
		<packet id="0x1c" name="SM_PLAYER_INFO">
			<part name="x" type="f"/>
			<part name="y" type="f"/>
			<part name="z" type="f"/>
			<part name="objId" type="d"/>
			<part name="raceSex" type="d"/>
			<part name="raceSex" type="d"/>
			<part name="0x00" type="c"/>
			<part name="0x26" type="c"/>
			<part name="raceId" type="c"/>
			<part name="classId" type="c"/>
			<part name="genderId" type="c"/>
			<part name="[0x01,9*0x00]" size="10" type="b"/>
			<part name="heading" type="c"/>
			<part name="name" type="S"/>
			<part name="TitleId" type="d"/>
			<part name="0x00" type="c"/>
			<part name="CastingSkillId" type="c"/>
			<part name="LegionMember" type="c"/>
			<part name="LegionId" type="c"/>
			<part name="[4*0xFF,15*0x00]" size="19" type="b"/>
			<part name="%hp" type="c"/>
			<part name="0x00" type="c"/>
			<part name="0x00" type="c"/>
			<part name="0x00" type="c"/>
			<part id="0" name="gears" type="bch"/>
			<for id="0">
				<part name="itemId" type="d"/>
				<part name="0x00" type="d"/>
				<part name="0x00" type="d"/>
				<part name="unk" type="h"/>
			</for>
			<part name="skinRGB" type="d">
				<reader type="Color"/>
			</part>
			<part name="hairRGB" type="d">
				<reader type="Color"/>
			</part>
			<part name="eyeRGB" type="d">
				<reader type="Color"/>
			</part>
			<part name="lipRGB" type="d">
				<reader type="Color"/>
			</part>
			<part name="face" type="c"/>
			<part name="hair" type="c"/>
			<part name="deco" type="c"/>
			<part name="tattoo" type="c"/>
			<part name="0x04" type="c"/>
			<part name="faceShape" type="c"/>
			<part name="foreHead" type="c"/>
			<part name="eyeHeight" type="c"/>
			<part name="eyeSpace" type="c"/>
			<part name="eyeWidth" type="c"/>
			<part name="eyeSize" type="c"/>
			<part name="eyeShape" type="c"/>
			<part name="eyeAngle" type="c"/>
			<part name="browHeight" type="c"/>
			<part name="browAngle" type="c"/>
			<part name="browShape" type="c"/>
			<part name="nose" type="c"/>
			<part name="noseBridge" type="c"/>
			<part name="noseWidth" type="c"/>
			<part name="noseTip" type="c"/>
			<part name="cheek" type="c"/>
			<part name="lipHeight" type="c"/>
			<part name="mouthSize" type="c"/>
			<part name="lipSize" type="c"/>
			<part name="smile" type="c"/>
			<part name="lipShape" type="c"/>
			<part name="jawHeight" type="c"/>
			<part name="chinJut" type="c"/>
			<part name="earShape" type="c"/>
			<part name="headSize" type="c"/>
			<part name="0x00" type="c"/>
			<part name="shoulderSize" type="c"/>
			<part name="armLength" type="c"/>
			<part name="legLength" type="c"/>
			<part name="neck" type="c"/>
			<part name="neckLength" type="c"/>
			<part name="shoulders" type="c"/>
			<part name="torso" type="c"/>
			<part name="chest" type="c"/>
			<part name="waist" type="c"/>
			<part name="hips" type="c"/>
			<part name="armThickness" type="c"/>
