=== Sinien/aion-lightning-2/trunk/AL-Game/data/static_data/npcs/npcs.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:include schemaLocation="../stats/stats.xsd" />
	<xs:include schemaLocation="../items/item_templates.xsd" />

	<xs:include schemaLocation="../import.xsd" />

	<xs:element name="npc_templates" type="npcTemplates" />

	<xs:complexType name="npcTemplates">
		<xs:sequence>
			<xs:element ref="import" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="npc_template" type="npcTemplate" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="npcTemplate">
		<xs:sequence>
			<xs:element name="stats" type="npcStatsTemplate" />
			<xs:element name="equipment" type="npcEquipmentList" minOccurs="0" />
			<xs:element name="kisk_stats" type="KiskStats" minOccurs="0" />
		</xs:sequence>
		<xs:attribute name="npc_id" type="npcId" use="required" />
		<xs:attribute name="level" type="xs:byte" use="required" />
		<xs:attribute name="name_id" type="xs:int" use="required" />
		<xs:attribute name="title_id" type="xs:int" default="0" />
		<xs:attribute name="name" type="xs:string" default="" />
		<xs:attribute name="height" type="xs:float" default="0" />
		<xs:attribute name="talking_distance" type="xs:int" default="0" />
		<xs:attribute name="ammo_speed" type="xs:int" />
		<xs:attribute name="npc_type" type="npcType" use="required" />
		<xs:attribute name="rank" type="NpcRank" />
		<xs:attribute name="srange" type="xs:int" default="0" />
		<xs:attribute name="tribe" type="xs:string" />
		<xs:attribute name="race" type="Race" />
		<xs:attribute name="hpgauge" type="xs:int"/>
		<xs:attribute name="arank" type="xs:int"/>
		<xs:attribute name="arange" type="xs:int"/>
		<xs:attribute name="state" type="xs:int"/>
	</xs:complexType>

	<xs:complexType name="npcStatsTemplate">
		<xs:complexContent>
			<xs:extension base="statsTemplate">
				<xs:sequence />
				<xs:attribute name="run_speed_fight" type="xs:float" use="required" />
				<xs:attribute name="crit" type="xs:int" use="required" />
				<xs:attribute name="pdef" type="xs:int" use="required" />
				<xs:attribute name="mdef" type="xs:int" use="required" />
				<xs:attribute name="maxXp" type="xs:int" use="required" />
				<xs:attribute name="accuracy" type="xs:int" use="required" />
				<xs:attribute name="power" type="xs:int" use="required" />			
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="npcEquipmentList">
		<xs:sequence>
			<xs:element name="item" type="itemId" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="KiskStats">
		<xs:sequence />
		<xs:attribute name="usemask" type="xs:int" use="required" />
		<xs:attribute name="members" type="xs:int" use="required" />
		<xs:attribute name="resurrects" type="xs:int" use="required" />
	</xs:complexType>

	<xs:simpleType name="npcType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="ATTACKABLE" />
			<xs:enumeration value="AGGRESSIVE" />
			<xs:enumeration value="POSTBOX" />
			<xs:enumeration value="RESURRECT" />
			<xs:enumeration value="USEITEM" />
			<xs:enumeration value="PORTAL" />
			<xs:enumeration value="NON_ATTACKABLE" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="NpcRank">
		<xs:restriction base="xs:string">
			<xs:enumeration value="NORMAL" />
			<xs:enumeration value="ELITE" />
			<xs:enumeration value="JUNK" />
			<xs:enumeration value="HERO" />
			<xs:enumeration value="LEGENDARY" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="npcId">
		<xs:restriction base="xs:int">
			<xs:minInclusive value="200000"/>
			<xs:maxInclusive value="900000"/>
		</xs:restriction>
	</xs:simpleType>

</xs:schema>

=== Sinien/aion-lightning-2/trunk/AL-Game/data/static_data/npcs/npc_templates2.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<npc_templates xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="npcs.xsd">
	<npc_template hpgauge="3" tribe="GENERAL" srange="20" rank="NORMAL" npc_type="NON_ATTACKABLE" height="1.0" name="teleport statue" name_id="350737" level="3" npc_id="730264">
        <stats power="11" accuracy="11" maxXp="104" mdef="11" pdef="11" crit="11" run_speed_fight="0.0" magic_accuracy="11" parry="11" block="100" evasion="11" fly_speed="0.0" run_speed="0.0" walk_speed="0.0" maxHp="121"/>
    </npc_template>
	<npc_template npc_id="203834" level="40" name="nestor" name_id="351326" npc_type="NON_ATTACKABLE" height="2.0" title_id="350470" rank="NORMAL" race="ELYOS" tribe="GENERAL" srange="10" arange="2" arank="1000" hpgauge="3" state="6">
		<stats maxMp="2828" maxHp="9426" maxXp="20552" block="70" parry="70" mdef="70" pdef="70" crit="70" power="70" evasion="70" accuracy="70" magic_accuracy="70" walk_speed="1.5" run_speed="6.0" run_speed_fight="4.2" fly_speed="0.0"/>
		<equipment>
			<item>114100294</item>
			<item>111100277</item>
			<item>125001508</item>
			<item>113100276</item>
			<item>112100256</item>
			<item>110100298</item>
		</equipment>
	</npc_template>
	<npc_template npc_id="203901" level="45" name="telemachus" name_id="351700" npc_type="NON_ATTACKABLE" height="0.85" title_id="350503" rank="LEGENDARY" race="ELYOS" tribe="GUARD" srange="20" arange="2" arank="1000" hpgauge="27" state="6">
		<stats maxMp="2057919" maxHp="6859729" maxXp="440709" block="139" parry="139" mdef="139" pdef="139" crit="139" power="139" evasion="139" accuracy="139" magic_accuracy="139" walk_speed="1.5" run_speed="6.0" run_speed_fight="7.0" fly_speed="0.0"/>
		<equipment>
			<item>114600312</item>
			<item>111600321</item>
			<item>113600313</item>
			<item>100000046</item>
			<item>112600306</item>
			<item>110600341</item>
		</equipment>
	</npc_template>
	<npc_template npc_id="203927" level="45" name="adelphie" name_id="351726" npc_type="NON_ATTACKABLE" height="1.0" title_id="350440" rank="NORMAL" race="ELYOS" tribe="GENERAL" srange="10" arange="2" arank="1000" hpgauge="3" state="85">
		<stats maxMp="3564" maxHp="11878" maxXp="27751" block="77" parry="77" mdef="77" pdef="77" crit="77" power="77" evasion="77" accuracy="77" magic_accuracy="77" walk_speed="1.5" run_speed="6.0" run_speed_fight="7.0" fly_speed="0.0"/>
		<equipment>
			<item>114100294</item>
			<item>111100277</item>
			<item>113100276</item>
			<item>112100256</item>
			<item>110100294</item>
		</equipment>
	</npc_template>
		<npc_template npc_id="203941" level="45" name="paion" name_id="351740" npc_type="NON_ATTACKABLE" height="1.2" rank="ELITE" race="ELYOS" tribe="GUARD" srange="15" arange="2" arank="1000" hpgauge="14" state="70">
		<stats maxMp="38277" maxHp="127590" maxXp="44466" block="93" parry="93" mdef="93" pdef="93" crit="93" power="93" evasion="93" accuracy="93" magic_accuracy="93" walk_speed="1.5" run_speed="6.0" run_speed_fight="8.0" fly_speed="0.0"/>
		<equipment>
			<item>114500320</item>
			<item>111500316</item>
			<item>125000638</item>
			<item>113500308</item>
			<item>100000385</item>
			<item>112500300</item>
			<item>110500325</item>
		</equipment>
	</npc_template>
	<npc_template npc_id="203943" level="45" name="turiel" name_id="351742" npc_type="NON_ATTACKABLE" height="1.0" rank="NORMAL" race="ELYOS" tribe="GENERAL" srange="10" arange="2" arank="1000" hpgauge="3" state="70">
		<stats maxMp="3564" maxHp="11878" maxXp="27751" block="77" parry="77" mdef="77" pdef="77" crit="77" power="77" evasion="77" accuracy="77" magic_accuracy="77" walk_speed="1.5" run_speed="6.0" run_speed_fight="4.2" fly_speed="0.0"/>
		<equipment>
			<item>114100294</item>
			<item>111100277</item>
			<item>113100276</item>
			<item>100000385</item>
			<item>112100256</item>
			<item>110100294</item>
		</equipment>
	</npc_template>
	<npc_template npc_id="203961" level="45" name="nikias" name_id="351760" npc_type="NON_ATTACKABLE" height="1.0" title_id="350430" rank="NORMAL" race="ELYOS" tribe="GENERAL" srange="10" arange="2" arank="1000" hpgauge="3" state="6">
		<stats maxMp="3564" maxHp="11878" maxXp="27751" block="77" parry="77" mdef="77" pdef="77" crit="77" power="77" evasion="77" accuracy="77" magic_accuracy="77" walk_speed="1.5" run_speed="6.0" run_speed_fight="4.2" fly_speed="0.0"/>
		<equipment>
			<item>114100294</item>
			<item>111100277</item>
			<item>113100276</item>
			<item>112100256</item>
			<item>110100294</item>
		</equipment>
	</npc_template>
	<npc_template npc_id="203995" level="45" name="hylas" name_id="351784" npc_type="NON_ATTACKABLE" height="1.2" rank="ELITE" race="ELYOS" tribe="GUARD" srange="15" arange="2" arank="1000" hpgauge="14" state="85">
		<stats maxMp="34798" maxHp="115991" maxXp="45329" block="93" parry="93" mdef="93" pdef="93" crit="93" power="93" evasion="93" accuracy="93" magic_accuracy="93" walk_speed="1.5" run_speed="6.0" run_speed_fight="8.0" fly_speed="0.0"/>
		<equipment>
			<item>114500320</item>
			<item>111500316</item>
			<item>125000638</item>
			<item>113500308</item>
			<item>100000065</item>
			<item>112500300</item>
			<item>110500325</item>
		</equipment>
	</npc_template>
	<npc_template npc_id="204006" level="43" name="demokritos" name_id="351794" npc_type="NON_ATTACKABLE" height="1.2" rank="ELITE" race="ELYOS" tribe="GUARD" srange="10" arange="4" arank="1000" hpgauge="14" state="85">
		<stats maxMp="27050" maxHp="90164" maxXp="40601" block="89" parry="89" mdef="89" pdef="89" crit="89" power="89" evasion="89" accuracy="89" magic_accuracy="89" walk_speed="1.5" run_speed="6.0" run_speed_fight="8.0" fly_speed="0.0"/>
		<equipment>
			<item>114300302</item>
			<item>111300276</item>
			<item>113300288</item>
			<item>100200092</item>
			<item>112300259</item>
			<item>100200092</item>
			<item>110300301</item>
		</equipment>
	</npc_template>
	<npc_template npc_id="204014" level="45" name="ophelia" name_id="351802" npc_type="NON_ATTACKABLE" height="1.0" rank="NORMAL" race="ELYOS" tribe="GENERAL" srange="10" arange="2" arank="1000" hpgauge="3" state="70">
		<stats maxMp="3564" maxHp="11878" maxXp="27751" block="77" parry="77" mdef="77" pdef="77" crit="77" power="77" evasion="77" accuracy="77" magic_accuracy="77" walk_speed="1.5" run_speed="6.0" run_speed_fight="4.2" fly_speed="0.0"/>
		<equipment>
			<item>114100294</item>
			<item>111100277</item>
			<item>113100276</item>
			<item>100000385</item>
			<item>112100256</item>
			<item>110100294</item>
		</equipment>
	</npc_template>
	<npc_template npc_id="260202" level="50" name="fortress mage" name_id="306870" npc_type="ATTACKABLE" height="1.05" rank="ELITE" race="ASMODIANS" tribe="GENERALDA_ALIDR" srange="20" arange="37" arank="1000" hpgauge="12">
		<stats maxMp="28076" maxHp="93586" maxXp="55529" block="102" parry="102" mdef="102" pdef="102" crit="102" power="102" evasion="102" accuracy="102" magic_accuracy="102" walk_speed="1.457" run_speed="6.0" run_speed_fight="7.0" fly_speed="0.0"/>
		<equipment>
			<item>114600508</item>
			<item>111600522</item>
			<item>125200004</item>
			<item>113600517</item>
			<item>100600028</item>
			<item>112600504</item>
			<item>110600552</item>
		</equipment>
	</npc_template>
	<npc_template npc_id="260203" level="50" name="fortress mage" name_id="306871" npc_type="ATTACKABLE" height="1.05" rank="ELITE" race="DRAKAN" tribe="GENERALDR_ALIDA" srange="20" arange="37" arank="1000" hpgauge="12">
		<stats maxMp="28076" maxHp="93586" maxXp="55529" block="102" parry="102" mdef="102" pdef="102" crit="102" power="102" evasion="102" accuracy="102" magic_accuracy="102" walk_speed="1.457" run_speed="6.0" run_speed_fight="7.0" fly_speed="0.0"/>
		<equipment>
			<item>100500284</item>
		</equipment>
	</npc_template>
	<npc_template npc_id="260383" level="50" name="fortress mage" name_id="308512" npc_type="ATTACKABLE" height="1.2" rank="ELITE" race="ASMODIANS" tribe="GUARD_DARK" srange="10" arange="37" arank="1000" hpgauge="12">
		<stats maxMp="28076" maxHp="93586" maxXp="55529" block="102" parry="102" mdef="102" pdef="102" crit="102" power="102" evasion="102" accuracy="102" magic_accuracy="102" walk_speed="1.457" run_speed="6.0" run_speed_fight="7.0" fly_speed="0.0"/>
		<equipment>
			<item>114600136</item>
			<item>111600135</item>
			<item>125200001</item>
			<item>113600128</item>
			<item>100600029</item>
			<item>112600123</item>
			<item>110600142</item>
		</equipment>
	</npc_template>
	<npc_template npc_id="263203" level="50" name="fortress mage" name_id="306906" npc_type="ATTACKABLE" height="1.05" rank="ELITE" race="ASMODIANS" tribe="GENERALDA_ALIDR" srange="20" arange="37" arank="1000" hpgauge="12">
		<stats maxMp="28076" maxHp="93586" maxXp="55529" block="102" parry="102" mdef="102" pdef="102" crit="102" power="102" evasion="102" accuracy="102" magic_accuracy="102" walk_speed="1.457" run_speed="6.0" run_speed_fight="7.0" fly_speed="0.0"/>
		<equipment>
			<item>114600508</item>
			<item>111600522</item>
			<item>125200004</item>
			<item>113600517</item>
			<item>100600028</item>
			<item>112600504</item>
			<item>110600552</item>
		</equipment>
	</npc_template>
	<npc_template npc_id="263504" level="50" name="fortress mage" name_id="306943" npc_type="ATTACKABLE" height="1.05" rank="ELITE" race="DRAKAN" tribe="GENERALDR_ALIDA" srange="20" arange="37" arank="1000" hpgauge="12">
		<stats maxMp="28076" maxHp="93586" maxXp="55529" block="102" parry="102" mdef="102" pdef="102" crit="102" power="102" evasion="102" accuracy="102" magic_accuracy="102" walk_speed="1.457" run_speed="6.0" run_speed_fight="7.0" fly_speed="0.0"/>
		<equipment>
			<item>100500284</item>
		</equipment>
	</npc_template>
