=== Sinien/aion-lightning-2/trunk/AL-Game/data/static_data/quest_script_data/quest_script_data.xsd
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:include schemaLocation="../quest_data/quest_data.xsd" />
	<xs:include schemaLocation="../import.xsd" />
	
	<xs:element name="quest_scripts" type="QuestScripts" />
	
	<xs:complexType name="QuestScripts">
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			<xs:element ref="import" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="item_collecting" type="ItemCollectingData" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="report_to" type="ReportToData" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="monster_hunt" type="MonsterHuntData" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="work_order" type="WorkOrdersData" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="xml_quest" type="XmlQuestData" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="QuestScriptData" abstract="true" >
		<xs:attribute name="id" type="xs:int" use="required" />
	</xs:complexType>

       <xs:complexType name="XmlQuestData">
       	<xs:complexContent>
			<xs:extension base="QuestScriptData">
                <xs:sequence>
                        <xs:element name="on_talk_event" type="OnTalkEvent" minOccurs="0" maxOccurs="unbounded" />
                        <xs:element name="on_kill_event" type="OnKillEvent" minOccurs="0" maxOccurs="unbounded" />
                </xs:sequence>
                <xs:attribute name="start_npc_id" type="xs:int" />
                <xs:attribute name="end_npc_id" type="xs:int" />
             </xs:extension>
          </xs:complexContent>
        </xs:complexType>

        <xs:complexType name="QuestCondition" abstract="true" >
                <xs:attribute name="op" type="ConditionOperation" use="required" />
        </xs:complexType>
        
        <xs:complexType name="QuestOperation" abstract="true" />

        <xs:complexType name="QuestEvent" abstract="true" >
                <xs:sequence>
                        <xs:element name="conditions" type="QuestConditions" minOccurs="0" maxOccurs="1" />
                        <xs:element name="operations" type="QuestOperations" minOccurs="0" maxOccurs="1" />
                </xs:sequence>
                <xs:attribute name="ids" type="NumberListType" />
        </xs:complexType>

	<xs:complexType name="QuestNpc">
		<xs:sequence>
			<xs:element name="dialog" type="QuestDialog" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:int" use="required" />
	</xs:complexType>

	<xs:complexType name="QuestVar">
		<xs:sequence>
			<xs:element name="npc" type="QuestNpc" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="value" type="xs:int" use="required" />
	</xs:complexType>

	<xs:complexType name="QuestDialog">
		<xs:sequence>
			<xs:element name="conditions" type="QuestConditions" minOccurs="0" maxOccurs="1" />
            <xs:element name="operations" type="QuestOperations" minOccurs="0" maxOccurs="1" />
		</xs:sequence>
		<xs:attribute name="id" type="xs:int" use="required" />
	</xs:complexType>

        <xs:complexType name="OnTalkEvent">
                <xs:complexContent>
                        <xs:extension base="QuestEvent">
                        	<xs:sequence>
								<xs:element name="var" type="QuestVar" minOccurs="0" maxOccurs="unbounded"/>
							</xs:sequence>
                        </xs:extension>
                </xs:complexContent>
        </xs:complexType>

        <xs:complexType name="OnKillEvent">
                <xs:complexContent>
                        <xs:extension base="QuestEvent">
                        	<xs:sequence>
								<xs:element name="monster_infos" type="MonsterInfo" minOccurs="0" maxOccurs="unbounded"/>
								<xs:element name="complite" type="QuestOperations" minOccurs="0" maxOccurs="1"/>
							</xs:sequence>
                        </xs:extension>
                </xs:complexContent>
        </xs:complexType>

        <xs:complexType name="QuestConditions">
                <xs:sequence minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="dialog_id" type="DialogIdCondition" minOccurs="0" maxOccurs="unbounded" />
                        <xs:element name="npc_id" type="NpcIdCondition" minOccurs="0" maxOccurs="unbounded" />
                        <xs:element name="pc_inventory" type="PcInventoryCondition" minOccurs="0" maxOccurs="unbounded" />
                        <xs:element name="quest_status" type="QuestStatusCondition" minOccurs="0" maxOccurs="unbounded" />
                        <xs:element name="quest_var" type="QuestVarCondition" minOccurs="0" maxOccurs="unbounded" />
                </xs:sequence>
                <xs:attribute name="operate" type="ConditionUnionType" use="required" />
        </xs:complexType>

        <xs:complexType name="QuestOperations">
                <xs:sequence minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="give_item" type="GiveItemOperation" minOccurs="0" maxOccurs="unbounded" />
                        <xs:element name="set_quest_var" type="SetQuestVarOperation" minOccurs="0" maxOccurs="unbounded" />
                        <xs:element name="npc_dialog" type="NpcDialogOperation" minOccurs="0" maxOccurs="unbounded" />
                        <xs:element name="set_quest_status" type="SetQuestStatusOperation" minOccurs="0" maxOccurs="unbounded" />
                        <xs:element name="start_quest" type="StartQuestOperation" minOccurs="0" maxOccurs="unbounded" />
                        <xs:element name="take_item" type="TakeItemOperation" minOccurs="0" maxOccurs="unbounded" />
                        <xs:element name="collect_items" type="CollectItemQuestOperation" minOccurs="0" maxOccurs="unbounded" />
                        <xs:element name="npc_use" type="ActionItemUseOperation" minOccurs="0" maxOccurs="unbounded" />
                        <xs:element name="kill" type="KillOperation" minOccurs="0" maxOccurs="unbounded" />
                </xs:sequence>
                <xs:attribute name="override" type="xs:boolean" default="true" />
        </xs:complexType>

        <xs:complexType name="DialogIdCondition">
                <xs:complexContent>
                        <xs:extension base="QuestCondition">
                                <xs:attribute name="value" type="xs:int" use="required" />
                        </xs:extension>
                </xs:complexContent>
        </xs:complexType>
        
        <xs:complexType name="NpcIdCondition">
                <xs:complexContent>
                        <xs:extension base="QuestCondition">
                                <xs:attribute name="values" type="xs:int" use="required" />
                        </xs:extension>
                </xs:complexContent>
        </xs:complexType>

        <xs:complexType name="PcInventoryCondition">
                <xs:complexContent>
                        <xs:extension base="QuestCondition">
                                <xs:attribute name="item_id" type="xs:int" use="required" />
                                <xs:attribute name="count" type="xs:long" use="required" />
                        </xs:extension>
                </xs:complexContent>
        </xs:complexType>
        
        <xs:complexType name="QuestStatusCondition">
                <xs:complexContent>
                        <xs:extension base="QuestCondition">
                                <xs:attribute name="value" type="QuestStatus" use="required" />
                                <xs:attribute name="quest_id" type="xs:int" />
                        </xs:extension>
                </xs:complexContent>
        </xs:complexType>
        
        <xs:complexType name="QuestVarCondition">
                <xs:complexContent>
                        <xs:extension base="QuestCondition">
                                <xs:attribute name="value" type="xs:int" use="required" />
                                <xs:attribute name="var_id" type="xs:int" use="required" />
                        </xs:extension>
                </xs:complexContent>
        </xs:complexType>
        
        <xs:complexType name="GiveItemOperation">
                <xs:complexContent>
                        <xs:extension base="QuestOperation">
                                <xs:attribute name="item_id" type="xs:int" use="required" />
                                <xs:attribute name="count" type="xs:int" use="required" />
                        </xs:extension>
                </xs:complexContent>
        </xs:complexType>

        <xs:complexType name="SetQuestVarOperation">
                <xs:complexContent>
                        <xs:extension base="QuestOperation">
                                <xs:attribute name="var_id" type="xs:int" use="required" />
                                <xs:attribute name="value" type="xs:int" use="required" />
                        </xs:extension>
                </xs:complexContent>
        </xs:complexType>

        <xs:complexType name="NpcDialogOperation">
                <xs:complexContent>
                        <xs:extension base="QuestOperation">
                                <xs:attribute name="id" type="xs:int" use="required" />
                                <xs:attribute name="quest_id" type="xs:int"/>
                        </xs:extension>
                </xs:complexContent>
        </xs:complexType>

        <xs:complexType name="SetQuestStatusOperation">
                <xs:complexContent>
                        <xs:extension base="QuestOperation">
                                <xs:attribute name="status" type="QuestStatus" use="required" />
                        </xs:extension>
                </xs:complexContent>
        </xs:complexType>

        <xs:complexType name="KillOperation">
                <xs:complexContent>
                        <xs:extension base="QuestOperation"/>
                </xs:complexContent>
        </xs:complexType>

        <xs:complexType name="StartQuestOperation">
                <xs:complexContent>
                        <xs:extension base="QuestOperation">
                                <xs:attribute name="id" type="xs:int" use="required" />
                        </xs:extension>
                </xs:complexContent>
        </xs:complexType>

        <xs:complexType name="CollectItemQuestOperation">
                <xs:complexContent>
                        <xs:extension base="QuestOperation">
                                <xs:sequence>
                                	<xs:element name="true" type="QuestOperations" minOccurs="1" maxOccurs="1"/>
                                	<xs:element name="false" type="QuestOperations" minOccurs="1" maxOccurs="1"/>
                                </xs:sequence>
                                <xs:attribute name="removeItems" type="xs:boolean" default="true"/>
                        </xs:extension>
                </xs:complexContent>
        </xs:complexType>

        <xs:complexType name="ActionItemUseOperation">
                <xs:complexContent>
                        <xs:extension base="QuestOperation">
                                <xs:sequence>
                                	<xs:element name="finish" type="QuestOperations" minOccurs="1" maxOccurs="1"/>
                                </xs:sequence>
                        </xs:extension>
                </xs:complexContent>
        </xs:complexType>
 
        <xs:complexType name="TakeItemOperation">
                <xs:complexContent>
                        <xs:extension base="QuestOperation">
                                <xs:attribute name="item_id" type="xs:int" use="required" />
                                <xs:attribute name="count" type="xs:int" use="required"/>
                        </xs:extension>
                </xs:complexContent>
        </xs:complexType>

        <xs:simpleType name="ConditionUnionType">
                <xs:restriction base="xs:string">
                        <xs:enumeration value="AND" />
                        <xs:enumeration value="OR" />
                </xs:restriction>
        </xs:simpleType>
        
                <xs:simpleType name="ConditionOperation">
                <xs:restriction base="xs:string">
                        <xs:enumeration value="EQUAL" />
                        <xs:enumeration value="GREATER" />
                        <xs:enumeration value="GREATER_EQUAL" />
                        <xs:enumeration value="LESSER" />
                        <xs:enumeration value="LESSER_EQUAL" />
                        <xs:enumeration value="NOT_EQUAL" />
                        <xs:enumeration value="IN" />
                        <xs:enumeration value="NOT_IN" />
                </xs:restriction>
        </xs:simpleType>

        <xs:simpleType name="QuestStatus">
                <xs:restriction  base="xs:string">
                        <xs:enumeration value="NONE" />
                        <xs:enumeration value="START" />
                        <xs:enumeration value="REWARD" />
                        <xs:enumeration value="COMPLETE" />
                        <xs:enumeration value="LOCKED" />
                </xs:restriction>
        </xs:simpleType>




	<xs:complexType name="ItemCollectingData">
		<xs:complexContent>
			<xs:extension base="QuestScriptData">
				<xs:attribute name="start_npc_id" type="xs:int" use="required"/>
				<xs:attribute name="action_item_id" type="xs:int" default="0"/>
				<xs:attribute name="end_npc_id" type="xs:int" default="0"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="ReportToData">
		<xs:complexContent>
			<xs:extension base="QuestScriptData">
				<xs:attribute name="start_npc_id" type="xs:int" use="required"/>
				<xs:attribute name="end_npc_id" type="xs:int" use="required"/>
				<xs:attribute name="item_id" type="xs:int" default="0"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="MonsterHuntData">
		<xs:complexContent>
			<xs:extension base="QuestScriptData">
				<xs:sequence>
					<xs:element name="monster_infos" type="MonsterInfo" minOccurs="1" maxOccurs="unbounded"/>
				</xs:sequence>
				<xs:attribute name="start_npc_id" type="xs:int" use="required"/>
				<xs:attribute name="end_npc_id" type="xs:int" default="0"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="WorkOrdersData">
		<xs:complexContent>
			<xs:extension base="QuestScriptData">
				<xs:sequence>
					<xs:element name="give_component" type="QuestItems" minOccurs="1" maxOccurs="unbounded"/>
				</xs:sequence>
				<xs:attribute name="start_npc_id" type="xs:int" use="required"/>
				<xs:attribute name="recipe_id" type="xs:int" use="required"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="MonsterInfo" >
		<xs:attribute name="var_id" type="xs:int" use="required"/>
		<xs:attribute name="min_var_value" type="xs:int" default="0"/>
		<xs:attribute name="max_kill" type="xs:int" use="required"/>
		<xs:attribute name="npc_id" type="xs:int" use="required"/>
	</xs:complexType>
	
</xs:schema>

=== Sinien/aion-lightning-2/trunk/AL-Game/data/static_data/quest_script_data/poeta.xml
<quest_scripts xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="quest_script_data.xsd">
<!--
  ~ This file is part of aion-unique.
  ~
  ~ aion-unique is free software: you can redistribute it and/or modify
  ~ it under the terms of the GNU General Public License as published by
  ~ the Free Software Foundation, either version 3 of the License, or
  ~ (at your option) any later version.
  ~
  ~ aion-unique is distributed in the hope that it will be useful,
  ~ but WITHOUT ANY WARRANTY; without even the implied warranty of
  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  ~ GNU General Public License for more details.
  ~
  ~ You should have received a copy of the GNU General Public License
  ~ along with aion-unique.  If not, see <http://www.gnu.org/licenses/>.
  -->

<!-- Start Poeta http://www.aionarmory.com/search.aspx?browse=4.3.1#quests:0+2+1 -->
	<!-- Prologue handled by script -->
	<!-- The Kerub Threat handled by script -->
	<!-- Request of the Elim handled by script -->
	<!-- Illegal Logging handled by script -->
	<!-- Neutralizing Odium handled by script -->
	<!-- Barring the Gate handled by script -->
	<!-- Kalio's Call handled by script -->
	<!-- Sleeping on the Job -->
	<report_to id="1101" start_npc_id="203049" end_npc_id="203057"/>
	<!-- Kerubar Hunt -->
	<monster_hunt id="1102" start_npc_id="203057">
		<monster_infos npc_id="210133" var_id="0" max_kill="3"/>
		<monster_infos npc_id="210134" var_id="0" max_kill="3"/>
		<monster_infos npc_id="210705" var_id="0" max_kill="3"/>
	</monster_hunt>
	<!-- Grain Thieves -->
	<item_collecting id="1103" start_npc_id="203057" action_item_id="700105"/>
	<!-- Report to Polina -->
	<report_to id="1104" start_npc_id="203057" end_npc_id="203059"/>
	<!-- The Snuffler Headache -->
	<item_collecting id="1105" start_npc_id="203050"/>
	<!-- Helping Kales -->
	<report_to id="1106" start_npc_id="203050" end_npc_id="203061" item_id="182200203"/>
	<!-- The Lost Axe handled by script -->
	<!-- Unos Ingredients -->
	<item_collecting id="1108" start_npc_id="203061"/>
	<!-- Abandoned Goods -->
	<item_collecting id="1109" start_npc_id="798007" action_item_id="700106"/>
	<!-- A Book for Namus -->
	<report_to id="1110" start_npc_id="203065" end_npc_id="203075" item_id="182200206"/>
	<!-- Insomnia Medicine handled by script -->
	<!-- To Fish in Peace -->
	<monster_hunt id="1112" start_npc_id="203072">
		<monster_infos npc_id="210259"  var_id="0" max_kill="5"/>
		<monster_infos npc_id="210260"  var_id="0" max_kill="5"/>
		<monster_infos npc_id="210672"  var_id="0" max_kill="5"/>
		<monster_infos npc_id="210065"  var_id="1" max_kill="5"/>
		<monster_infos npc_id="210066"  var_id="1" max_kill="5"/>
	</monster_hunt>
	<!-- Mushroom Thieves -->
	<monster_hunt id="1113" start_npc_id="203076">
		<monster_infos npc_id="210262"  var_id="0" max_kill="8"/>
		<monster_infos npc_id="210675"  var_id="0" max_kill="8"/>
	</monster_hunt>
	<!-- The Nymph's Gown handled by script -->
	<!-- The Elim's Message -->
	<xml_quest id="1115" start_npc_id="203075" end_npc_id="203058">
		<on_talk_event ids="203072 203058">
			<var value="0">
				<npc id="203072">
					<dialog id="25">
						<operations>
							<npc_dialog id="1352"/>
						</operations>
					</dialog>
					<dialog id="10000">
						<operations>
							<set_quest_var var_id="0" value="1"/>
							<npc_dialog id="1352" quest_id="0"/>
						</operations>
					</dialog>
				</npc>
			</var>
			<var value="1">
				<npc id="203058">
					<dialog id="25">
						<operations>
							<npc_dialog id="2375"/>
						</operations>
					</dialog>
					<dialog id="1009">
						<operations override="false">
							<set_quest_status status="REWARD"/>
						</operations>
					</dialog>
				</npc>
			</var>
		</on_talk_event>
	</xml_quest>
	<!-- Pernos's Robe -->
	<item_collecting id="1116" start_npc_id="203060"/>
	<!-- Light up the Night -->
	<item_collecting id="1117" start_npc_id="203074"/>
	<!-- Polinia's Ointment -->
	<report_to id="1118" start_npc_id="203059" end_npc_id="203079" item_id="182200224"/>
	<!-- A Taste of Namus's Medicine -->
	<report_to id="1119" start_npc_id="203075" end_npc_id="203080" item_id="182200225"/>
	<!-- Thinning out Worgs -->
	<monster_hunt id="1120" start_npc_id="203082">
		<monster_infos npc_id="210143"  var_id="0" max_kill="9"/>
		<monster_infos npc_id="210142"  var_id="0" max_kill="9"/>
	</monster_hunt>
	<!-- Oz's Prayer Beads -->
	<item_collecting start_npc_id="203081" id="1121"/>
	<!-- Delivering Pernos's Robe handled by script -->
	<!-- Where's Tutty? handled by script -->
	<!-- Avenging Tutty -->
	<item_collecting id="1124" start_npc_id="790001"/>
	<!-- Suspicious Ore -->
	<item_collecting id="1125" start_npc_id="203085" action_item_id="700107"/>
	<!-- Mushroom Research -->
	<item_collecting start_npc_id="203079" id="1126"/>
	<!-- Ancient Cube -->
	<xml_quest id="1127" start_npc_id="798008" end_npc_id="798008">
		<on_talk_event ids="700001">
			<conditions operate="AND">
				<quest_status value="START" op="EQUAL"/>
			</conditions>
			<var value="0">
				<npc id="700001">
					<dialog id="-1">
						<operations>
							<npc_use>
								<finish>
									<give_item item_id="182200215" count="1"/>
									<set_quest_var var_id="0" value="1"/>
								</finish>
							</npc_use>
						</operations>
					</dialog>
				</npc>
			</var>
			<var value="1">
				<npc id="798008">
					<dialog id="25">
						<operations>
							<npc_dialog id="2375"/>
						</operations>
					</dialog>
					<dialog id="33">
						<operations>
							<collect_items>
								<true>
									<set_quest_status status="REWARD"/>
									<npc_dialog id="5"/>
								</true>
								<false>
									<npc_dialog id="2716"/>
								</false>
							</collect_items>
						</operations>
					</dialog>
				</npc>
			</var>
		</on_talk_event>
	</xml_quest>
	<!-- Scouting Timolia Mine -->
	<item_collecting start_npc_id="203085" id="1129"/>
	<!-- A New Skill handled by script-->
	<!-- Collecting Aria -->
	<item_collecting id="1206" start_npc_id="203059"/>
	<!-- Tula's Music Box -->
	<item_collecting start_npc_id="203082" end_npc_id="203085" id="1207"/>
</quest_scripts>

=== Sinien/aion-lightning-2/trunk/AL-Game/data/static_data/quest_script_data/ishalgen.xml
<quest_scripts xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="quest_script_data.xsd">
	<!--
  ~ This file is part of aion-unique.
  ~
  ~ aion-unique is free software: you can redistribute it and/or modify
  ~ it under the terms of the GNU General Public License as published by
  ~ the Free Software Foundation, either version 3 of the License, or
  ~ (at your option) any later version.
  ~
  ~ aion-unique is distributed in the hope that it will be useful,
  ~ but WITHOUT ANY WARRANTY; without even the implied warranty of
  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  ~ GNU General Public License for more details.
  ~
  ~ You should have received a copy of the GNU General Public License
  ~ along with aion-unique.  If not, see <http://www.gnu.org/licenses/>.
  -->
	<!-- http://www.aionarmory.com/search.aspx?browse=4.3.5#quests:0+2+1 -->
	<!-- Prologue handled by script -->
	<!-- Thinking Ahead handled by script-->
	<!-- Where's Rae? Handled by script.-->
	<!-- Treasure of the Deceased handled by script-->
	<!-- A Charmed Cube handled by script -->
	<!-- Teaching a Lesson handled by script -->
	<!-- Hit Them Where it Hurts handled by script -->
	<!-- Where's Rae This Time? handled by script -->
	<!-- Order of the Captain handled by script -->
	<!-- On Your Feet! -->
	<report_to id="2101" start_npc_id="203500" end_npc_id="203504"/>
	<!-- A Bloody Task -->
	<monster_hunt id="2102" start_npc_id="203504">
		<monster_infos npc_id="210364" var_id="0" max_kill="4"/>
		<monster_infos npc_id="210363" var_id="0" max_kill="4"/>
	</monster_hunt>
	<!-- The Sprigg Report -->
	<report_to id="2103" start_npc_id="203504" end_npc_id="203501"/>
	<!-- Meeting the Fruit Quota -->
	<item_collecting id="2104" start_npc_id="203502" action_item_id="700124"/>
	<!-- Sparkle and Shine -->
	<item_collecting id="2105" start_npc_id="203502"/>
	<!-- Vanar's Flattery -->
	<report_to start_npc_id="203502" end_npc_id="203517" item_id="182203106" id="2106"/>
	<!-- Return to Sender handled by script-->
	<!-- The Shinier the Better -->
	<item_collecting id="2108" start_npc_id="798037"/>
	<!-- Love in Bloom -->
	<item_collecting id="2109" start_npc_id="203532" action_item_id="700125"/>
	<!-- Idle Hands -->
	<report_to start_npc_id="203522" end_npc_id="203533" item_id="182203110" id="2110"/>
	<!-- Urd's Request -->
	<item_collecting start_npc_id="790003" id="2112"/>
	<!-- Token of a Lost Love -->
	<item_collecting start_npc_id="203534" id="2113"/>
	<!-- The Insect Problem handled by script-->
	<!-- Sap for Leather -->
	<report_to start_npc_id="203534" end_npc_id="203515" item_id="182203114" id="2115"/>
	<!-- A Treasure Map -->
	<item_collecting start_npc_id="203541" action_item_id="700139" id="2116"/>
	<!-- Food Bandits -->
	<monster_hunt start_npc_id="203540" id="2117">
		<monster_infos npc_id="210389" var_id="0" max_kill="9"/>
	</monster_hunt>
	<!-- Up to no Good -->
	<item_collecting id="2118" start_npc_id="203539"/>
	<!-- Black Opal -->
	<item_collecting start_npc_id="203541" id="2119" action_item_id="700127"/>
	<!-- A Brax Skin Rug -->
	<item_collecting start_npc_id="203542" id="2120"/>
	<!-- Checking on a Friend -->
	<report_to start_npc_id="203540" end_npc_id="203547" item_id="182203119" id="2121"/>
	<!-- Ashes to Ashes handled by script-->
	<!-- The Imprisoned Gourmet handled by script -->
	<!-- The Captain's Secret -->
	<item_collecting id="2124" start_npc_id="203548"/>
	<!-- The Robbery Plot handled by script -->
	<!-- As Much as You Can Carry -->
	<item_collecting id="2126" start_npc_id="203544" action_item_id="700129"/>
	<!-- Pearls Before Swine -->
	<item_collecting id="2127" start_npc_id="203544"/>
	<!-- A Good Tonic -->
	<item_collecting id="2128" start_npc_id="203543"/>
	<!-- Suspicious Activity -->
	<monster_hunt id="2129" start_npc_id="203552">
		<monster_infos var_id="0" npc_id="210408" max_kill="1"/>
		<monster_infos var_id="1" npc_id="210409" max_kill="1"/>
	</monster_hunt>
	<!-- A Delivery of Leather -->
	<report_to start_npc_id="203515" end_npc_id="203542" item_id="182203129" id="2131"/>
	<!-- A New Skill handled by script -->
	<!-- Azpha For Health And Well-being -->
	<item_collecting id="2133" start_npc_id="203519"/>
	<!-- Alfrigh's Request -->
	<item_collecting id="2134" start_npc_id="203543"/>
	<!-- For Love of Negi handled by script -->
	<!-- The Lost Axe handled by script -->
	<!-- A Cursed Opal -->
	<report_to start_npc_id="203539" end_npc_id="203541" id="2137"/>
</quest_scripts>
