=== Sinien/aion-lightning-2/trunk/AL-Game/data/static_data/quest_script_data/quest_script_data.xsd
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:include schemaLocation="../quest_data/quest_data.xsd" />
	<xs:include schemaLocation="../import.xsd" />
	
	<xs:element name="quest_scripts" type="QuestScripts" />
	
	<xs:complexType name="QuestScripts">
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			<xs:element ref="import" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="item_collecting" type="ItemCollectingData" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="report_to" type="ReportToData" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="monster_hunt" type="MonsterHuntData" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="work_order" type="WorkOrdersData" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="xml_quest" type="XmlQuestData" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="QuestScriptData" abstract="true" >
		<xs:attribute name="id" type="xs:int" use="required" />
	</xs:complexType>

       <xs:complexType name="XmlQuestData">
       	<xs:complexContent>
			<xs:extension base="QuestScriptData">
                <xs:sequence>
                        <xs:element name="on_talk_event" type="OnTalkEvent" minOccurs="0" maxOccurs="unbounded" />
                        <xs:element name="on_kill_event" type="OnKillEvent" minOccurs="0" maxOccurs="unbounded" />
                </xs:sequence>
                <xs:attribute name="start_npc_id" type="xs:int" />
                <xs:attribute name="end_npc_id" type="xs:int" />
             </xs:extension>
          </xs:complexContent>
        </xs:complexType>

        <xs:complexType name="QuestCondition" abstract="true" >
                <xs:attribute name="op" type="ConditionOperation" use="required" />
        </xs:complexType>
        
        <xs:complexType name="QuestOperation" abstract="true" />

        <xs:complexType name="QuestEvent" abstract="true" >
                <xs:sequence>
                        <xs:element name="conditions" type="QuestConditions" minOccurs="0" maxOccurs="1" />
                        <xs:element name="operations" type="QuestOperations" minOccurs="0" maxOccurs="1" />
                </xs:sequence>
                <xs:attribute name="ids" type="NumberListType" />
        </xs:complexType>

	<xs:complexType name="QuestNpc">
		<xs:sequence>
			<xs:element name="dialog" type="QuestDialog" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:int" use="required" />
	</xs:complexType>

	<xs:complexType name="QuestVar">
		<xs:sequence>
			<xs:element name="npc" type="QuestNpc" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="value" type="xs:int" use="required" />
	</xs:complexType>

	<xs:complexType name="QuestDialog">
		<xs:sequence>
			<xs:element name="conditions" type="QuestConditions" minOccurs="0" maxOccurs="1" />
            <xs:element name="operations" type="QuestOperations" minOccurs="0" maxOccurs="1" />
		</xs:sequence>
		<xs:attribute name="id" type="xs:int" use="required" />
	</xs:complexType>

        <xs:complexType name="OnTalkEvent">
                <xs:complexContent>
                        <xs:extension base="QuestEvent">
                        	<xs:sequence>
								<xs:element name="var" type="QuestVar" minOccurs="0" maxOccurs="unbounded"/>
							</xs:sequence>
                        </xs:extension>
                </xs:complexContent>
        </xs:complexType>

        <xs:complexType name="OnKillEvent">
                <xs:complexContent>
                        <xs:extension base="QuestEvent">
                        	<xs:sequence>
								<xs:element name="monster_infos" type="MonsterInfo" minOccurs="0" maxOccurs="unbounded"/>
								<xs:element name="complite" type="QuestOperations" minOccurs="0" maxOccurs="1"/>
							</xs:sequence>
                        </xs:extension>
                </xs:complexContent>
        </xs:complexType>

        <xs:complexType name="QuestConditions">
                <xs:sequence minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="dialog_id" type="DialogIdCondition" minOccurs="0" maxOccurs="unbounded" />
                        <xs:element name="npc_id" type="NpcIdCondition" minOccurs="0" maxOccurs="unbounded" />
                        <xs:element name="pc_inventory" type="PcInventoryCondition" minOccurs="0" maxOccurs="unbounded" />
                        <xs:element name="quest_status" type="QuestStatusCondition" minOccurs="0" maxOccurs="unbounded" />
                        <xs:element name="quest_var" type="QuestVarCondition" minOccurs="0" maxOccurs="unbounded" />
                </xs:sequence>
                <xs:attribute name="operate" type="ConditionUnionType" use="required" />
        </xs:complexType>

        <xs:complexType name="QuestOperations">
                <xs:sequence minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="give_item" type="GiveItemOperation" minOccurs="0" maxOccurs="unbounded" />
                        <xs:element name="set_quest_var" type="SetQuestVarOperation" minOccurs="0" maxOccurs="unbounded" />
                        <xs:element name="npc_dialog" type="NpcDialogOperation" minOccurs="0" maxOccurs="unbounded" />
                        <xs:element name="set_quest_status" type="SetQuestStatusOperation" minOccurs="0" maxOccurs="unbounded" />
                        <xs:element name="start_quest" type="StartQuestOperation" minOccurs="0" maxOccurs="unbounded" />
                        <xs:element name="take_item" type="TakeItemOperation" minOccurs="0" maxOccurs="unbounded" />
                        <xs:element name="collect_items" type="CollectItemQuestOperation" minOccurs="0" maxOccurs="unbounded" />
                        <xs:element name="npc_use" type="ActionItemUseOperation" minOccurs="0" maxOccurs="unbounded" />
                        <xs:element name="kill" type="KillOperation" minOccurs="0" maxOccurs="unbounded" />
                </xs:sequence>
                <xs:attribute name="override" type="xs:boolean" default="true" />
        </xs:complexType>

        <xs:complexType name="DialogIdCondition">
                <xs:complexContent>
                        <xs:extension base="QuestCondition">
                                <xs:attribute name="value" type="xs:int" use="required" />
                        </xs:extension>
                </xs:complexContent>
        </xs:complexType>
        
        <xs:complexType name="NpcIdCondition">
                <xs:complexContent>
                        <xs:extension base="QuestCondition">
                                <xs:attribute name="values" type="xs:int" use="required" />
                        </xs:extension>
                </xs:complexContent>
        </xs:complexType>

        <xs:complexType name="PcInventoryCondition">
                <xs:complexContent>
                        <xs:extension base="QuestCondition">
                                <xs:attribute name="item_id" type="xs:int" use="required" />
                                <xs:attribute name="count" type="xs:long" use="required" />
                        </xs:extension>
                </xs:complexContent>
        </xs:complexType>
        
        <xs:complexType name="QuestStatusCondition">
                <xs:complexContent>
                        <xs:extension base="QuestCondition">
                                <xs:attribute name="value" type="QuestStatus" use="required" />
                                <xs:attribute name="quest_id" type="xs:int" />
                        </xs:extension>
                </xs:complexContent>
        </xs:complexType>
        
        <xs:complexType name="QuestVarCondition">
                <xs:complexContent>
                        <xs:extension base="QuestCondition">
                                <xs:attribute name="value" type="xs:int" use="required" />
                                <xs:attribute name="var_id" type="xs:int" use="required" />
                        </xs:extension>
                </xs:complexContent>
        </xs:complexType>
        
        <xs:complexType name="GiveItemOperation">
                <xs:complexContent>
                        <xs:extension base="QuestOperation">
                                <xs:attribute name="item_id" type="xs:int" use="required" />
                                <xs:attribute name="count" type="xs:int" use="required" />
                        </xs:extension>
                </xs:complexContent>
        </xs:complexType>

        <xs:complexType name="SetQuestVarOperation">
                <xs:complexContent>
                        <xs:extension base="QuestOperation">
                                <xs:attribute name="var_id" type="xs:int" use="required" />
                                <xs:attribute name="value" type="xs:int" use="required" />
                        </xs:extension>
                </xs:complexContent>
        </xs:complexType>

        <xs:complexType name="NpcDialogOperation">
                <xs:complexContent>
                        <xs:extension base="QuestOperation">
                                <xs:attribute name="id" type="xs:int" use="required" />
                                <xs:attribute name="quest_id" type="xs:int"/>
                        </xs:extension>
                </xs:complexContent>
        </xs:complexType>

        <xs:complexType name="SetQuestStatusOperation">
                <xs:complexContent>
                        <xs:extension base="QuestOperation">
                                <xs:attribute name="status" type="QuestStatus" use="required" />
                        </xs:extension>
                </xs:complexContent>
        </xs:complexType>

        <xs:complexType name="KillOperation">
                <xs:complexContent>
                        <xs:extension base="QuestOperation"/>
                </xs:complexContent>
        </xs:complexType>

        <xs:complexType name="StartQuestOperation">
                <xs:complexContent>
                        <xs:extension base="QuestOperation">
                                <xs:attribute name="id" type="xs:int" use="required" />
                        </xs:extension>
                </xs:complexContent>
        </xs:complexType>

        <xs:complexType name="CollectItemQuestOperation">
                <xs:complexContent>
                        <xs:extension base="QuestOperation">
                                <xs:sequence>
                                	<xs:element name="true" type="QuestOperations" minOccurs="1" maxOccurs="1"/>
                                	<xs:element name="false" type="QuestOperations" minOccurs="1" maxOccurs="1"/>
                                </xs:sequence>
                                <xs:attribute name="removeItems" type="xs:boolean" default="true"/>
                        </xs:extension>
                </xs:complexContent>
        </xs:complexType>

        <xs:complexType name="ActionItemUseOperation">
                <xs:complexContent>
                        <xs:extension base="QuestOperation">
                                <xs:sequence>
                                	<xs:element name="finish" type="QuestOperations" minOccurs="1" maxOccurs="1"/>
                                </xs:sequence>
                        </xs:extension>
                </xs:complexContent>
        </xs:complexType>
 
        <xs:complexType name="TakeItemOperation">
                <xs:complexContent>
                        <xs:extension base="QuestOperation">
                                <xs:attribute name="item_id" type="xs:int" use="required" />
                                <xs:attribute name="count" type="xs:int" use="required"/>
                        </xs:extension>
                </xs:complexContent>
        </xs:complexType>

        <xs:simpleType name="ConditionUnionType">
                <xs:restriction base="xs:string">
                        <xs:enumeration value="AND" />
                        <xs:enumeration value="OR" />
                </xs:restriction>
        </xs:simpleType>
        
                <xs:simpleType name="ConditionOperation">
                <xs:restriction base="xs:string">
                        <xs:enumeration value="EQUAL" />
                        <xs:enumeration value="GREATER" />
                        <xs:enumeration value="GREATER_EQUAL" />
                        <xs:enumeration value="LESSER" />
                        <xs:enumeration value="LESSER_EQUAL" />
                        <xs:enumeration value="NOT_EQUAL" />
                        <xs:enumeration value="IN" />
                        <xs:enumeration value="NOT_IN" />
                </xs:restriction>
        </xs:simpleType>

        <xs:simpleType name="QuestStatus">
                <xs:restriction  base="xs:string">
                        <xs:enumeration value="NONE" />
                        <xs:enumeration value="START" />
                        <xs:enumeration value="REWARD" />
                        <xs:enumeration value="COMPLETE" />
                        <xs:enumeration value="LOCKED" />
                </xs:restriction>
        </xs:simpleType>




	<xs:complexType name="ItemCollectingData">
		<xs:complexContent>
			<xs:extension base="QuestScriptData">
				<xs:attribute name="start_npc_id" type="xs:int" use="required"/>
				<xs:attribute name="action_item_id" type="xs:int" default="0"/>
				<xs:attribute name="end_npc_id" type="xs:int" default="0"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="ReportToData">
		<xs:complexContent>
			<xs:extension base="QuestScriptData">
				<xs:attribute name="start_npc_id" type="xs:int" use="required"/>
				<xs:attribute name="end_npc_id" type="xs:int" use="required"/>
				<xs:attribute name="item_id" type="xs:int" default="0"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="MonsterHuntData">
		<xs:complexContent>
			<xs:extension base="QuestScriptData">
				<xs:sequence>
					<xs:element name="monster_infos" type="MonsterInfo" minOccurs="1" maxOccurs="unbounded"/>
				</xs:sequence>
				<xs:attribute name="start_npc_id" type="xs:int" use="required"/>
				<xs:attribute name="end_npc_id" type="xs:int" default="0"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="WorkOrdersData">
		<xs:complexContent>
			<xs:extension base="QuestScriptData">
				<xs:sequence>
					<xs:element name="give_component" type="QuestItems" minOccurs="1" maxOccurs="unbounded"/>
				</xs:sequence>
				<xs:attribute name="start_npc_id" type="xs:int" use="required"/>
				<xs:attribute name="recipe_id" type="xs:int" use="required"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="MonsterInfo" >
		<xs:attribute name="var_id" type="xs:int" use="required"/>
		<xs:attribute name="min_var_value" type="xs:int" default="0"/>
		<xs:attribute name="max_kill" type="xs:int" use="required"/>
		<xs:attribute name="npc_id" type="xs:int" use="required"/>
	</xs:complexType>
	
</xs:schema>

=== Sinien/aion-lightning-2/trunk/AL-Game/data/static_data/quest_script_data/sanctum.xml
<quest_scripts xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="quest_script_data.xsd">
	<!--
  ~ This file is part of aion-unique.
  ~
  ~ aion-unique is free software: you can redistribute it and/or modify
  ~ it under the terms of the GNU General Public License as published by
  ~ the Free Software Foundation, either version 3 of the License, or
  ~ (at your option) any later version.
  ~
  ~ aion-unique is distributed in the hope that it will be useful,
  ~ but WITHOUT ANY WARRANTY; without even the implied warranty of
  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  ~ GNU General Public License for more details.
  ~
  ~ You should have received a copy of the GNU General Public License
  ~ along with aion-unique.  If not, see <http://www.gnu.org/licenses/>.
  -->
	<!-- Symbol of the Chosen -->
	<report_to id="9510" start_npc_id="203752" end_npc_id="203711"/>
	<!-- A Ring Imbued With Aether handled by Script-->
	<!-- A Song Of Praise handled by script -->
	<!-- Delivery for the Outer Port -->
	<xml_quest id="1963" start_npc_id="203726" end_npc_id="203726">
		<on_talk_event ids="203851">
			<var value="0">
				<npc id="203851">
					<dialog id="25">
						<operations>
							<npc_dialog id="1352"/>
						</operations>
					</dialog>
					<dialog id="10000">
						<operations>
							<set_quest_var var_id="0" value="1"/>
							<set_quest_status status="REWARD"/>
						</operations>
					</dialog>
				</npc>
			</var>
		</on_talk_event>
	</xml_quest>
	<!-- Krallic Language Potion handled by script-->
	<!-- TODO: Ulaguru Speaks -->
	<!-- [Craft] A Betua Wood Offering -->
	<item_collecting id="1905" start_npc_id="203792"/>
	<!-- [Craft] A Token of Respect -->
	<item_collecting id="1906" start_npc_id="203786"/>
	<!-- [Craft] Crafting Ingots -->
	<item_collecting id="1902" start_npc_id="203788"/>
	<!-- [Craft] First Steps in Tailoring -->
	<item_collecting id="1907" start_npc_id="203793"/>
	<!-- [Craft] Ingot Ingredients -->
	<item_collecting id="1903" start_npc_id="203701"/>
	<!-- [Craft] Roasting Inina -->
	<item_collecting id="1904" start_npc_id="203784"/>
	<!-- TODO: [Event] Chasing the Grankers -->
	<!-- TODO: [Event] Festival of Daevas -->
	<!-- TODO: [Event] Solorius Donations -->
	<!-- TODO: [Event] Solorius Invitations -->
	<!-- TODO: [Event] Thirst for Invention! -->
	<!-- TODO: A Lingering Mystery -->
	<!-- TODO: An Ax For Namus -->
	<!-- The Seed of Evil -->
	<item_collecting id="1910" start_npc_id="203833"/>
	<!-- Marmeia's Krall Research -->
	<item_collecting id="1911" start_npc_id="203864"/>
	<!-- Familiar Food -->
	<item_collecting id="1912" start_npc_id="203864"/>
	<!-- TODO: Guide of Life -->
	<!-- TODO: Intention of Lady Yustiel -->
	<!-- TODO: Meaning of Life -->
	<!-- TODO: Teachings of Life -->
	<!-- TODO: A Souvenir For Noris -->
	<xml_quest id="1964" start_npc_id="203726" end_npc_id="203726">
		<on_talk_event ids="203776">
			<var value="0">
				<npc id="203776">
					<dialog id="25">
						<operations>
							<npc_dialog id="1352"/>
						</operations>
					</dialog>
					<dialog id="10000">
						<operations>
							<set_quest_var var_id="0" value="1"/>
							<set_quest_status status="REWARD"/>
						</operations>
					</dialog>
				</npc>
			</var>
		</on_talk_event>
	</xml_quest>
	<!-- A Costume on Consignment -->
	<report_to id="1986" start_npc_id="798009" end_npc_id="203810"/>
	<!-- TODO: Chasing a Criminal -->
	<!-- TODO: Secret Library Access -->
	<!-- D'yer Ma'ker -->
	<item_collecting id="1971" start_npc_id="203812"/>
	<!-- TODO: A Helmet Gone Astray -->
	<!-- TODO: A Robe Gone Astray -->
	<!-- TODO: A Staff Gone Astray -->
	<!-- TODO: A Sword Gone Astray -->
	<!-- TODO: Combat Potions -->
	<!-- TODO: Combat Rations -->
	<!-- TODO: Esoteric Book of Illusion -->
	<!-- TODO: Esoteric Book of Justice -->
	<!-- TODO: Esoteric Book of Life -->
	<!-- TODO: Esoteric Freedom Book -->
	<!-- A Mended Robe -->
	<report_to id="1956" start_npc_id="203793" end_npc_id="278511" item_id="182206029"/>
	<!-- TODO: A Package From Vulcanus -->
	<!-- Getting a Grip -->
	<report_to id="1953" start_npc_id="203792" end_npc_id="278510" item_id="182206026"/>
	<!-- Never Short of Steel -->
	<report_to id="1951" start_npc_id="203788" end_npc_id="278510" item_id="182206024"/>
	<!-- Nuts to Denegos -->
	<report_to id="1954" start_npc_id="203784" end_npc_id="278507" item_id="182206027"/>
	<!-- Spellbook Express -->
	<report_to id="1955" start_npc_id="203786" end_npc_id="278510" item_id="182206028"/>
	<!-- TODO: A Letter to Medea -->
	<!-- TODO: A Bigger Warehouse -->
	<!-- A Lucky Day -->
	<report_to id="1947" start_npc_id="203795" end_npc_id="798012"/>
	<!-- TODO: Wings of Mastery -->
	<!-- TODO: A Passion For Tailoring -->
	<!-- TODO: Alchemy Expert -->
	<!-- TODO: Armorsmithing Expert -->
	<!-- TODO: Cooking Expert -->
	<!-- TODO: Handicrafting Expert -->
	<!-- TODO: Passion for Alchemy -->
	<!-- TODO: Passion for Armorsmithing -->
	<!-- TODO: Passion for Cooking -->
	<!-- TODO: Passion for Handicrafting -->
	<!-- TODO: Passion for Weaponsmithing -->
	<!-- TODO: Requirements For Tailoring Expert -->
	<!-- TODO: Requirements for Alchemy Expert -->
	<!-- TODO: Requirements for Armorsmithing Expert -->
	<!-- TODO: Requirements for Cooking Expert -->
	<!-- TODO: Requirements for Handicrafting Expert -->
	<!-- TODO: Requirements for Weaponsmithing Expert -->
	<!-- TODO: Tailoring Expert -->
	<!-- TODO: [Expert] Weaponsmithing Expert -->
	<!-- TODO: [Top Expert] Alchemy Expert -->
	<!-- TODO: [Top Expert] Armorsmithing Expert -->
	<!-- TODO: [Top Expert] Cooking Expert -->
	<!-- TODO: [Top Expert] Handicrafting Expert -->
	<!-- TODO: [Top Expert] Passion for Alchemy -->
	<!-- TODO: [Top Expert] Passion for Armorsmithing -->
	<!-- TODO: [Top Expert] Passion for Cooking -->
	<!-- TODO: [Top Expert] Passion for Handicrafting -->
	<!-- TODO: [Top Expert] Passion for Tailoring -->
	<!-- TODO: [Top Expert] Passion for Weaponsmithing -->
	<!-- TODO: [Top Expert] Requirements for Alchemy Expert -->
	<!-- TODO: [Top Expert] Requirements for Armorsmithing Expert -->
	<!-- TODO: [Top Expert] Requirements for Cooking Expert -->
	<!-- TODO: [Top Expert] Requirements for Handicrafting Expert -->
	<!-- TODO: [Top Expert] Requirements for Tailoring Expert -->
	<!-- TODO: [Top Expert] Requirements for Weaponsmithing Expert -->
	<!-- TODO: [Top Expert] Tailoring Expert -->
	<!-- TODO: [Top Expert] Weaponsmithing Expert -->
	<!-- TODO: The Assassin Preceptor's Task -->
	<!-- TODO: The Chanter Preceptor's Task -->
	<!-- TODO: The Cleric Preceptor's Task -->
	<!-- TODO: The Gladiator Preceptor's Task -->
	<!-- TODO: The Ranger Preceptor's Task -->
	<!-- TODO: The Sorcerer Preceptor's Task -->
	<!-- TODO: The Spiritmaster Preceptor's Task -->
	<!-- TODO: The Templar Preceptor's Task -->
	<!-- TODO: To Catch a Dragon -->
	<!-- TODO: [Growth] Flora's First Charm -->
	<!-- A Gift For Vindachinerk -->
	<item_collecting id="1949" start_npc_id="279006"/>
	<!-- TODO: Where's Vindachinerk? -->
	<!-- TODO: Black Cloud Fakery -->
	<!-- Flame Sword -->
	<item_collecting id="1930" start_npc_id="203767"/>
	<!-- TODO: Going out of Business -->
	<!-- TODO: A Matter of Reputation -->
	<!-- TODO: [Growth] Flora's Second Charm -->
	<!-- TODO: Shameless Peperinrinerk -->
	<!-- TODO: [Group] A Promise to a Customer -->
	<!-- TODO: Hairpin Ahoy! -->
	<!-- TODO: Rules of Alchemy and Life -->
	<!-- TODO: [Group] Snow Blessing -->
	<!-- TODO: The Manduri Imperative -->
	<!-- TODO: The Pirates' Log -->
	<!-- TODO: A Disturbing Report -->
	<!-- TODO: Tissue? I Don't Even Know You! -->
	<!-- What Nerison Saw -->
	<report_to id="1936" start_npc_id="203833" end_npc_id="204573"/>
	<!-- TODO: RM-78c -->
	<!-- TODO: A Lepharist Monstrosity -->
	<!-- TODO: Bring Back the Booty -->
	<!-- TODO: Plunder the Pirates -->
	<!-- TODO: [Group] Rescue Haorunerk! -->
	<!-- TODO: Revenge of Himusus -->
	<!-- TODO: [Group] Steel Rake Spy -->
	<!-- TODO: [Group] The Difficulties of Beauty -->
	<!-- TODO: [Group] The Missing Cube Craftsman -->
	<!-- TODO: The Pirates' Pouch -->
	<!-- Goodwill of Kuruminerk -->
	<report_to id="3960" start_npc_id="798322" end_npc_id="203711"/>
	<!-- TODO: Destruction and Rebirth -->
	<!-- TODO: Fire and Ice -->
	<!-- TODO: [Growth] Flora's Third Charm -->
	<!-- TODO: [Group] To Master the Dragon -->
	<!-- TODO: Epilogue -->
	<!-- TODO: Koruchinerk's Offer -->
	<!-- TODO: Mutual Benefits -->
	<!-- TODO: Shoshinerk's Reward -->
	<!-- TODO: The Balaur Report -->
	<!-- TODO: [Group] Gathering the Surkana -->
	<!-- TODO: [Group] Obtaining the Dragel -->
	<!-- TODO: [Group] Obtaining the Drazma -->
	<!-- TODO: [Group] The Danger of Drana -->
	<!-- TODO: [Group] The Secret of Surkana -->
	<!-- TODO: [Growth] Flora's Fourth Charm -->
</quest_scripts>
